= Metanorma
:technical-committee-number: 46
:docnumber: XXXXX
:tc-document-number: 9999
:edition: 1
:ref-docnumber: ISO XXXXX:2018(E)
:copyright-year: 2018
:language: en
:title-intro-en: Information and documentation
:title-main-en: Standards reference model
:title-intro-fr: Information et documentation
:title-main-fr: ****
:doctype: international-standard
:docstage: 10
:docsubstage: 92
:technical-committee-type: TC
:technical-committee-number: 46
:technical-committee: Information and documentation
:subcommittee-type: SC
:subcommittee-number: 9
:subcommittee: Identification and description
:workgroup-type: WG
:workgroup-number: 15
:workgroup: Bibliography
:secretariat: ANSI
:language: en
:script: Latn
:draft:
:toc:
:stem:
:xrefstyle: short
:local-cache-only:
:data-uri-image:

[[foreword]]
.Foreword
ISO (the International Organization for Standardization)
is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

The procedures used to develop this document and those intended for its further maintenance are described in the ISO/IEC Directives, Part 1. In particular the different approval criteria needed for the different types of ISO documents should be noted. This document was drafted in accordance with the editorial rules of the ISO/IEC Directives, Part 2 (see www.iso.org/directives).

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights. Details of any patent rights identified during the development of the document will be in the Introduction and/or on the ISO list of patent declarations received (see www.iso.org/patents).

Any trade name used in this document is information given for the convenience of users and does not constitute an endorsement.

For an explanation on the voluntary nature of standards, the meaning of ISO specific terms and expressions related to conformity assessment, as well as information about ISO's adherence to the World Trade Organization (WTO) principles in the Technical Barriers to Trade (TBT) see the following URL: www.iso.org/iso/foreword.html.

This document was prepared by Technical Committee ISO/TC {technical-committee-number}, _{technical-committee}_.

This is the first edition of this document.

[[introduction]]

:sectnums!:
== Introduction

The process of generating standards documents is problematic, and becoming more so with the increased work burden on standards organisations. ISO is no exception to this issue, and concerns have been raised over both the efficiency and the effectiveness of the workflows around generating standards in those bodies and elsewhere.

* The rigorous and detailed directives around document structure articulated in <<isoiecdir2>> are being manually validated by the editorial teams, with mixed results.
* Editing of documents substantially revolves around Microsoft Word toolsets, with all the problems that conflating document structure and presentation introduce. The editorial process has to spend significant amounts of time on formatting rather than document content, and is vulnerable to error. Opportunities to automate document presentation independently of content (as is routinely done in the HTML world with CSS) are not being taken up.
* Existing exchange mechanisms for documents have been claimed to focus on document appearance, rather than document structure, and so do not alleviate the formatting burden on the editorial process.
* Different standards have completely different workflows, with different inputs: anyone submitting the same standards text to more than one standard body has to replicate a significant amount of work.
* Within the ISO community, subcommittees are resorting to extreme measures such as always having a national body put in a negative vote in DIS or DAM ballots, in order to force a text review, and to reduce the large number of content and formatting errors that routinely occur in published standards.

These problems are if anything even more acute in other standards bodies. The Chinese National Standards body's counterpart to <<isoiecdir2>>, <<gbt11>>, is rather more prescriptive than <<isoiecdir2>> about formatting; despite support of standards authoring through an exhaustive Microsoft Word template wizard, the adherence of published standards to <<gbt11>> is haphazard at best. The wizard provided by the Chinese National Standards body was a Windows-specific tool written in 2010 that no longer works on contemporary systems -- which highlights another vulnerability with using proprietary tools to support standards production.

We have identified a need for a standards document production process that leverages a non-WYSIWYG approach to document production, such as has been used for years in instances like LaTeX, HTML, and DocBook, and more recently Markdown and Asciidoctor. We have also identified a need for the process to be based on a formal document model, such as is seen in DocBook, HTML, and TEI, which can be validated against, and which is able to deal with the particular needs of standards documents.

In this document, we propose Metanorma as such a standards document production process. The process centers around the Metanorma document model, which is intended to encompass the core similarities between standards bodies' versions of standards documents; particularities of different standards bodies are kept to a minimum, and expressed as local extensions. The process generates a semantic representation of the standards document expressed in the abstract document model, based on non-WYSIWYG, lightly marked-up text-based input. A further step then generates different output formats from the same document model expression, treating them as the application of styling rather than as document editing.

This approach has the following benefits:

* The approach enables an end-to-end, author-to-publishing workflow, with well-managed artefacts along each stage, that editorial bodies can exercise appropriate control over. This becomes all the easier as each artefact until the very end is text rather than binary: that allows the document management infrastructure around computer source code (such as version control) to be used to manage standards document production.
* Much of the tedium and unpredictability around formatting documents to align with presentation requirements is automated, since the document model is semantic, and abstracted away from presentation. Formatting is applied only at the very end of the process. This includes not only formatting details such as margin sizes and font choices, but also autonumbering of sections and tables, cross-referencing, automated generation of references, and generating tables of contents.
* The structural and content requirements around standards documents can be captured in the document model, and documents can therefore be subject to formal validation against the model. That means that a Metanorma-based process can provide substantial feedback to authors on the extent to which they comply with the rules expressed in specifications like <<isoiecdir2>> -- including rules around wording (e.g. where requirements can occur), as well as document structure.
* The document model is substantially the same across standards, as is the non-WYSIWYG text input that it is derived from. That means that text can be repurposed for different standards bodies with minimal effort: it is treated mostly as a swap-out of stylesheets, with only minor adjustments needed to content.

Currently the Metanorma process is realised in the Ruby programming language, with the non-WYSIWYG text input expressed in Asciidoctor, and output generated in HTML, Microsoft Word (.doc), and PDF (generated from HTML). Because of the modular approach taken to the toolset, other input and output formats can be supported.

Development of Metanorma started in late 2017. Metanorma is already in used by standards authors for several standards:

* Draft submissions to ISO (all types: standards, guides, PAS, TR, TS...)
* CalConnect Standards (as its official format)
* IETF RFCs and Internet-Drafts (among official authoring methods)
* Chinese National Standards ("GB standards") (for draft submission)
* Cloud Security Alliance Documents (workgroup outputs)


== Scope

This document provides the Metanorma reference model for standards documents. Implementation of the reference model and serialisation formats out of scope of this document.

The mapping of the reference model to output formats such as HTML, and the application of organisation-specific styling to those outputs, is out of scope of this document.

This document discusses processes around customising the reference model for different standards, and describes customisation for the ISO and CSD standards as example profiles in <<isoprofile>> and <<csdprofile>>. Prescribing profiles of the document model for particular standards, however, is out of scope of this document.

The modelling of bibliographies and bibliographic citations is part of the reference model, but is the subject of a separate proposal, <<relaton>>, and is not discussed in detail in this document.

The modelling of changes to documents is in scope of the _Basic Document_ model described here, but is not described in this document.

Markup conventions in text markup schemes (such as Asciidoctor) that enable generation of the reference model are out of scope of this document.

[bibliography]
== Normative References

// Surely the following boilerplate can be suppressed

The following documents are referred to in the text in such a way that some or
all of their content constitutes requirements of this document. For dated
references, only the edition cited applies. For undated references, the latest
edition of the referenced document (including any amendments) applies.

* [[[relaton,ISO xxxx:--]]] footnote:[In draft], _Information and documentation -- Bibliographic reference model and serialization_
* [[[rfc3986,IETF RFC 3986]]], _Uniform Resource Identifier (URI): Generic Syntax_
* [[[iso639,ISO 639 (all parts)]]], _Codes for the representation of names of languages_
* [[[iso8601,ISO 8601]]], _Data elements and interchange formats – Information interchange – Representation of dates and times_
* [[[iso10118,ISO 10118 (all parts)]]], _Information technology -- Security techniques -- Hash-functions_
* [[[iso14888,ISO 14888 (all parts)]]], _Information technology -- Security techniques -- Digital signatures with appendix_
* [[[iso15924,ISO 15924]]], _Information and documentation -- Codes for the representation of names of scripts_


== Terms and Definitions

[[term_standardizingbody]]
=== Standardizing body

[alt]#Standards body#

body that has recognized activities in standardization

[.source]
<<IEV,901-03-03>>

[[term_standard]]
=== Standard

[alt]#Standards document#

document, established by consensus and approved by a recognized _body_ (<<term_standardizingbody>>), that provides, for common and repeated use, rules, guidelines or characteristics for activities or their results, aimed at the achievement of the optimum degree of order in a given context

[.source]
<<IEV,901-02-02>>

[[term_class]]
=== Class

structure containing a description of an entity in terms of its components

=== Subclass

_class_ (<<term_class>>) which inherits from another class its component descriptions, and optionally adds to them its own component descriptions


[[term_documentmodel]]
=== Document model

[alt]#Model#

formal specification of the structure of a document in terms of its components and their arrangement, expressed through _classes_ (<<term_class>>)

=== Standards model

_document model_ (<<term_documentmodel>>) for _standards_ (<<term_standard>>)

[[term_paragraph]]
=== Paragraph

subdivision of running text, normally run on throughout, that is separated from text before and after by a change of line and stands below any chapters or sections (<<term_section>>)

[.source]
<<iso5127,clause 3.5.8.07>>

[[term_block]]
=== Block

_paragraph_ (<<term_paragraph>>)-level grouping of text

=== Inline Element

grouping of text that can be contained within a _paragraph_ (<<term_paragraph>>), including plain strings

[[term_section]]
=== Section

hierarchical subdivision of a document, consisting of one or more _blocks_ (<<term_block>>), and/or one or more sections

=== Identifier

a character, or group of characters, used to identify or name an item of data and possibly to indicate certain properties of that item

[.source]
<<IEV,714-21-07>>

=== Term

expression with a particular meaning that is part of the specialized vocabulary of a field


== Modelling

=== Structure

The Metanorma document model is expressed hierarchically.

* At its base is a _Basic Document_ model, which expresses the structure of generic documents.
* The _Basic Document_ model is specialised as a _Standards Document_ structure, conveying the structure particular to standards documents as a class.
* The Standards Document model is further specialised into models specific to particular standards.
* Specific standards models can form the basis in turn of other standards models. For example, the Chinese National Standards model, as described in <<gbt11>>, is structurally modelled after ISO documents, and is explicitly described as a localisation of the 2004 version of <<isoiecdir2-2004>>. So the Chinese Standards model is best expressed as a specialisation of the ISO Standards model.

Specialisation of a model consists of:

* Adding classes to a base model.
* Changing attributes of a base model class. This is not restricted to adding attributes, as is the case in typical entity subclassing; it can also include removing attributes from a class, changing their obligation and cardinality, and changing their type, including changing enumerations. Attributes can be overruled at any level; for example, standards-specific models routinely enhance the bibliographic model at the base of the hierarchy.
* For reasons of clarity, renaming classes and attributes is avoided in specialisation.

The classes involved in the document model are of three classes:

* Sections (<<basicsection>>, <<standardssection>>)
* Blocks (paragraph-level groupings of text) (<<basicblock>>, <<standardsblock>>)
* Inline elements (groupings of text smaller than a paragraph, including plain strings) (<<inline>>)

In the Metanorma model, the classes are in a strict hierarchical relation: documents consist of sections, which consist of blocks, which consist of inline elements. Sections can be nested within sections (e.g. clauses and subclauses); blocks can be nested within blocks (e.g. nested lists). Although the model does not currently provide for it, inline elements can also be embedded within other inline elements (e.g. bold + italics). However, sections are not expected to be siblings of blocks, nor blocks of inline elements. For example, a list (block) is not expected to occur next to inline text within a paragraph. For that reason, paragraphs cannot contain other block elements, such as lists or tables.

NOTE: This constraint is inherited from tools like Markdown and Asciidoctor, and is not present in XML-based schemas like HTML, TEI-C, or DocBook. It helps to simplify the document model significantly, and while it sacrifices some expressive potential, the difference is minor, particularly with regards to the rendering of paragraphs.

The _Basic Document_ model contains the bulk of the blocks and inline elements in the Metanorma model. The Standards Model and the standard-specific models mostly deal with the organisation of sections within a standards document.

The Metanorma document model depends on the <<iso690>> bibliography model for its expression of bibliographic references. The specific bibliography model instantiation and serialisation it uses is the subject of a separate proposal, <<relaton>>, and is not discussed further here.

=== Influences

The Metanorma document model has drawn on several existing models, with a view to reflecting the expressiveness of existing standards, but also to align with the capability of established document production tools.

The standards models consulted most closely for Metanorma are those for ISO standards <<isoiecdir2>> and IETF standards (<<rfc7749>>, <<rfc7991>>). The document production tools that Metanorma consciously sought to align with are HTML 4, HTML 5, Markdown, Asciidoctor (<<asciidoctor>>), and Microsoft Word. The modelling of blocks and inline elements in particular are closely aligned with HTML.

== Basic Document Model

[[basicdocument]]
=== Document

The _Basic Document_ model treats all documents as collections of _sections_ (<<basicsection>>). It also adds the following metadata as part of the document model:

// Please confirm what I've assumed here for identifier

`identifier`:: a globally unique identifier for the document in an agreed identifier schema. The identifier is to be used for tracking interactions with the document without depending on formal document registries; it would be exemplified by a GUID, rather than a document registry identifier such as "ISO 639", which belongs to `bibdata`.
`bibdata`:: a bibliographic description, capturing bibliographic metadata about the document itself, including authors, title, and date of production.
`version`:: information about the current version of the document, including an `edition` (represented in the _Basic Document_ model as an ordinal numeral), the date of latest revision (`revisionDate`), and a textual description of the current `draft`.
`integrityValue`:: an optional digital signature of the document (<<contributionelementmetadata>>).

.Basic Document model: Document
[plantuml]
....
include::basicdoc_uml/BasicDocument.wsd[]
....

The modelling of `bibdata` follows the _BibliographicItem_ class in <<relaton>>. Unlike the generic _BibliographicItem_ class, the `title` and `copyright` attributes of `bibdata` are mandatory.

.Basic Document model: bibdata
[plantuml]
....
include::basicdoc_uml/BibData.wsd[]
....

[[basicsection]]
=== Section

The _Basic Document_ model is generic in its application, and accordingly does not do detailed modelling of the differences between sections; that is deferred for the _Standards Document_ model. The _Basic Document_ model only recognises the following classes of section:

* _Basic Sections_, which are leaf nodes (do not contain any sections).
* _Hierarchical Sections_, which can contain other sections. Hierarchical Sections are modelled as a subclass of Basic Sections, so the hierarchical arrangement of sections can be arbitrarily deep.
* _Content Sections_, which in the _Basic Document_ model are treated as equivalent to Hierarchical Sections.
* _References Sections_, which are leaf nodes, and contain zero or more bibliographical references (as modelled in <<relaton>>).

All sections are modelled as having the following attributes:

`title`:: an optional title of the section.
`id`:: an optional identifier for the section, to be used for cross-references.
`blocks`:: zero or more text blocks, containing the textual content of the section (but excluding subsections, which are only present in Hierarchical Sections).
`notes`:: any notes whose scope is the entire section, rather than a specific block. Notes are modelled as a sequence of zero or more paragraphs.


NOTE: In the _Basic Document_ model, a section can contain both blocks of text and subsections; in rendering, the blocks of text are presumed to come before the subsections. The ISO document model proscribes the coocurrence of text and subsections in a clause (= section) as "hanging paragraphs"; that proscription is modelled as an override of the model specific to Standards documents, for which the referencing of clauses is a paramount concern (<<standardssection>>).

// TODO: refine reference

.Basic Document model: Section
[plantuml]
....
include::basicdoc_uml/Sections.wsd[]
....

[[basicblock]]
=== Block

Blocks of text are all modelled as subclasses of the _Basic Block_ class, which has the following attributes common to all blocks:

`id`:: an optional identifier for the block, to be used for cross-references.
`notes`:: any notes whose scope is the block. Notes are modelled as a sequence of zero or more paragraphs.
`contributionelementmetadata`:: attribution of the block to a specific contributor (<<contributionelementmetadata>>), to be used in change management of documents.

The _Basic Document_ model recognises the following classes of block:

* Paragraphs (<<basicpara>>)
* Multi-paragraph blocks: Blockquotes, Reviewer comments, Admonitions (<<basicmultipara>>)
* Tables (<<basictable>>)
* Lists (<<basiclist>>): Unordered lists, Ordered lists, Definition lists
* Figures (<<basicfigure>>)
* Sourcecode (<<basicsourcecode>>)
* Formulas (<<basicformula>>)
* Examples (<<basicexample>>)

Functionally figures, sourcecode, formulas and examples all play a similar role, as providing illustrative content that is ancillary to the main content. However each class has its own particular structure.


[[basicpara]]
==== Paragraph


Paragraphs can contain any sequence of inline elements (<<inline>>), and optionally a text alignment (`alignment`).

NOTE: Text alignment is the only concession the modelling of paragraphs makes to rendering, and is there because the application of alignment to paragraphs, while rare, is unpredictable from paragraph semantics. Other rendering attributes of paragraphs, such as spacing before and after, are considered to be semantically predictable and are relegated to document stylesheets.

Paragraphs have the following subclass:

* _Paragraph With Footnote_, which can also contain footnotes (<<footnote>>). The distinction is necessary, as footnotes are not appropriate for all instances of paragraph content (e.g. sourcecode annotations) (<<basicsourcecode>>).

.Basic Document model: Paragraph
[plantuml]
....
include::basicdoc_uml/Paragraphs.wsd[]
....

[[basicmultipara]]
==== Multi-paragraph blocks


The following classes of block are modelled as containing zero or more paragraphs:

* _Blockquote_, which also contains an optional bibliographic citation for the quotation (`source`), and an optional `author` of the quotation. The `author` attribute of the blockquote is redundant with the citation, since it restates  information about the author that should be recoverable from the citation itself. It is included for convenience, in case processing the citation is prohibitive for rendering tools, and is motivated by the separate inclusion of `author` as an attribute in blockquotes in Asciidoctor.
* _Admonition_, which captures sidebars to the main text conveying particular warnings to the reader. The Admonition block includes a type of admonition; the defined types for the _Basic Document_ model are _Warning, Note, Tip, Important, and Caution_.
* [[review]]_Review_, which is intended to capture reviewer comments about some text in the document. The Review block includes the following attributes: an optional string identifying the `reviewer` who offered the comment; an optional `date` when the comment was made; a mandatory identifier for the start of the text to which the comment applies (`appliesFrom`), and an optional identifier for the end of the text to which the comment applies (`appliesTo`).

NOTE: If the `appliesTo` identifier of a Review block is absent, the comment applies only to the span of text identified by the `appliesFrom` identifier; if it is present, the comments applies to the span of text between the start of the span of text identified by `appliesFrom`, and the end of the span of text identified by `appliesTo`.

NOTE: Admonition notes are modelled to be distinct from notes under sections or blocks.

.Basic Document model: Multi-paragraph Block
[plantuml]
....
include::basicdoc_uml/MultiParagraphs.wsd[]
....

[[basictable]]
==== Table


Tables are modelled following the same principles as HTML tables. They contain the following elements:

`name`:: An optional label for the table.
`head`:: Zero or more table rows constituting the table header.
`body`:: One or more table rows constituting the table body.
`foot`:: Zero or more table rows constituting the table footer.
`definitions`:: An optional definitions list (<<basiclist>>) defining any symbols used in the table. (This reflects practice in <<isoiecdir2>>.)

_Table rows_ are defined as a sequence of zero or more header cells and data cells (corresponding to HTML `th` and `td`), both classes being instances of table cells.

_Table cells_ contain either zero or more paragraphs with footnotes (<<basicpara>>), or zero or more text elements (<<textelements>>). In addition, they have the following optional rendering attributes which are aligned with HTML:

`colspan`:: Number of columns in the underlying table grid which the cell spans.
`rowspan`:: Number of rows in the underlying table grid which the cell spans.
`align`:: Textual alignment of the cell.

.Basic Document model: Table
[plantuml]
....
include::basicdoc_uml/Tables.wsd[]
....

[[basiclist]]
==== List

Lists are modelled following the same principles as HTML lists. All lists contain zero or more _list items_, which by default consist of an identifier (`id`), and one or more paragraphs with footnotes (<<basicpara>>). This allows individual list items in a list to be cross-referenced within the document.

Three subclasses of List are modelled.

* _Unordered lists_ are equivalent to the List base class.
* _Ordered lists_ are Lists with a `type` attribute, describing the kind of numeration applied to the List; the values allowed under the _Basic Document_ model are _roman, alphabet, arabic, roman_upper, alphabet_upper_, corresponding to lowercase Roman numerals, lowercase alphabetic letters, Arabic numerals, uppercase Roman numerals, and uppercase alphabetic letters.
* _Definition lists_ override the definition of the List Item to be a pair of `item` (zero or more text elements: <<textelements>>) and `definition` (zero or more paragraphs with footnotes: <<basicpara>>).

.Basic Document model: List
[plantuml]
....
include::basicdoc_uml/Lists.wsd[]
....

[[basicfigure]]
==== Figure

Figures are wrappers for images, and may themselves contain figures (_Subfigure_ class). They contain the following elements, all of which are optional:

`name`:: A label for the figure.
`image`:: An image (<<image>>).
`source`:: A URI or other reference intended to link to an externally hosted image (or equivalent).
`definitions`:: An optional definitions list (<<basiclist>>) defining any symbols used in the figure. (This reflects practice in <<isoiecdir2>>.)
`footnotes`:: Optional footnotes specific to the figure. (This reflects practice in <<isoiecdir2>>.)
`figure`:: Embedded figures. (This reflects practice in <<isoiecdir2>>, and subfigures are intended to be mutually exclusive with `image`, `source`: the latter are intended for leaf node figures.)

NOTE: The _Basic Document_ model makes no provision for "ASCII art", the use of text instead of images. Models derived from the _Basic Document_ model do permit such use of text by extending the modelling of figure (e.g. <<csdblock>>).

[[basicsourcecode]]
==== Sourcecode

Sourcecode blocks are wrappers for computer code or comparable text. They contain the following elements:

`name`:: A label for the source code.
`content`:: The computer code or other such text presented in the block, as a single unformatted string. (The string should be treated as preformatted text, with whitespace treated as significant.)
`callouts`:: Zero or more cross-references (<<crossreferences>>); these are intended to be embedded within the `content` string, and link to annotations.
`calloutAnnotations`:: These are annotations to the source code; each annotation consists of zero or more paragraphs, and is intended to be referenced by a callout within the source code.

[[basicformula]]
==== Formula

Formula blocks are wrappers for mathematical or other formulas. They contain the following elements:

`stem`:: A STEM element (<<textelements>>), constituting the content of the formula
`definitions`:: An optional definitions list (<<basiclist>>) defining any symbols used in the formula. (This reflects practice in <<isoiecdir2>>.)

[[basicexample]]
==== Example

Example blocks are wrappers for open-ended example text. They consist of a combination of any of the following blocks:

* Formula
* List
* Blockquote (which is how generic text is included in an example)
* Sourcecode

// TODO: I don't think we've enforced the blockquote restriction; should we, or should we just allow text elements as an alternative here?

.Basic Document model: Figure, Sourcecode, Formula, Example
[plantuml]
....
include::basicdoc_uml/MiscBlocks.wsd[]
....



[[inline]]
=== Inline Elements

==== General

Inline elements represent the components of text blocks. They are modelled in the _Basic Document_ model as _Basic Elements_.

All Basic Elements have the following attribute:

`contributionelementmetadata`:: attribution of the element to a specific contributor (<<contributionelementmetadata>>), to be used in change management of documents.

Three subclasses of Basic Elements are modelled:

* Text elements, which contain text and associated formatting information, but which do not contain any associated identifiers. (<<textelements>>)
* ID elements, which contain identifiers. (<<image>>)
* Reference elements, which contain references to identifiers. (<<crossreferences>>)

Footnotes (<<footnote>>) are a special case of Reference element, which are not included under Basic Elements because of the need to exclude them from certain classes of paragraph (<<basicpara>>).

[[textelements]]
==== Text Elements

The modelling of text elements is substantially derived from HTML, and encompasses semantically significant formatting of text. For example, it encompasses italics and boldface (under their semantic guise of `emphasis` and `strong`); but it omits different sizes of font, as information that is typically semantically predictable, and relegated to stylesheets.

All text elements contain a localised string (<<datavalues>>).

The following elements indicate formatting, and have no further attributes:

* Monospace (corresponding to HTML `tt`, `code`)
* Emphasis (corresponding to HTML `em`, `i`)
* Strong (corresponding to HTML `strong`, `b`)
* Superscript (corresponding to HTML `sup`)
* Subscript (corresponding to HTML `sub`)
* Strike (corresponding to HTML 4 `s`)
* Small Caps

Text Elements also include the STEM element, representing mathematical and other formulas. This consists of a `type`, indicating which language is used to express the formula, and the content of the formula itself. By default the _Basic Document_ model allows AsciiMath and MathML in STEM elements.

NOTE: The _Basic Document_ model does not provide for text elements containing other text elements, for simplicity (e.g. monospace + italics, or superscript + strikethrough). Extensions to the model may choose to model such nesting of text elements.

.Basic Document model: Text Elements
[plantuml]
....
include::basicdoc_uml/TextElements.wsd[]
....

==== Empty Elements

The following elements are subclasses of Basic Element that contain no text, and are intended to represent semantically significant formatting elements:

* Line Break (corresponding to HTML `br`)
* Page Break
* Horizontal Rule (corresponding to HTML `hr`)

.Basic Document model: Empty Elements
[plantuml]
....
include::basicdoc_uml/EmptyElements.wsd[]
....


[[image]]
==== ID Elements

ID Elements are inline elements that have an identifier (`id`), which permits them to be cross-referenced by Reference Elements (<<crossreferences>>). ID Elements in the _Basic Document_ model do not contain text.

There are two subclasses of ID Elements in the _Basic Document_ model:

* _Bookmarks_ are intended as anchors for cross-references which do not have scope over blocks or sections. Anchors within a block under the _Basic Document_ model cannot span across a number of inline elements; bookmarks are intended as point anchors. For that reason, the Review block (<<review>>) has a starting reference and an optional ending reference, which can be bookmarks as well as block or section references.
* _Images_ are containers for pictorial content. They have a `source`, indicating the URI of the image file; a `type`, indicating the type of the image file; and an optional `height` and `width` attribute, which can be an integer or "auto".

NOTE: The _Basic Document_ model does not encompass audio and video files, but any extensions to the model would treat them likewise as ID Elements.

// TODO: We have not put alt text in; should we? We have not tackled accessibility in general.

.Basic Document model: ID Elements
[plantuml]
....
include::basicdoc_uml/IdElements.wsd[]
....


[[crossreferences]]
==== Reference Elements

Reference Elements are inline elements which reference other elements in the document, or other documents. All Reference Elements are modelled as containing the following attributes:

`text`:: The optional, unformatted textual content of the reference element.
`type`:: The type of Reference Element, prescribing how it is to be rendered. The _Basic Document_ model recognises four types: _inline_ (referencing another element in the same document), _external_ (referencing an external document), _footnote_ (an inline reference to be rendered as a footnote), and _callout_ (an inline reference to be rendered as a callout: <<basicsourcecode>>).

The following subclasses of Reference Elements are modelled.

* Reference to Link Element: An external reference, whose `target` is defined as a URI.
* Reference to Citation Element: An external reference to a bibliographic entity, as modelled in <<relaton>> as a _citation_. In addition to the attributes of _citation_, the reference has an optional `normative` attribute (which may be used by those standards which differentiate normative and informative references), and optional `citeAs` attributes prescribing how the bibliographic citation should be rendered in the text.
* Reference to ID Element: An internal reference, whose `target` corresponds to the identifier of a section, block or ID Element within the current document.

The Reference to ID Element class in turn has the following subclasses modelled:

* Callout, for which the `type` is set to _callout_, and the `text` is constrained to be a single mandatory string. The target of the callout is understood to be the location of the callout within the source code; the extent of the target is not expressed overtly.
* Reference To ID With Paragraph Element, which associates both `text` and `content` to the cross-reference; the `content` is a sequence of one or more paragraphs (<<basicpara>>).

[[footnote]]
==== Footnote

Footnotes are modelled as a subclass of Reference To ID With Paragraph Element, which constrain their `type` to be _footnote_. The `text` attribute is the footnote reference, and the `content` attribute is the footnote contents.  The target of the footnote is understood to be the location of the footnote within the text; the extent of the target is not expressed overtly.

NOTE: Endnotes are not modelled separately from footnotes in the _Basic Document_ model, and the use of footnotes and endnotes as realisations of annotations are normally stylistic alternatives, which would be relegated to a stylesheet.

[[datavalues]]
=== Data Types

==== Basic Data Types

The following basic types are used in the definition of the _Basic Document_ model.

* String
* URI, as defined in <<rfc3986>>.
* Language names, as defined in <<iso639>>.
* Dates and times, as defined in <<iso8601>>.
* Hash algorithms, as defined in <<iso10118>>.
* Digital signature algorithms, as defined in <<iso14888>>.
* Script names, as defined in <<iso15924>>.
* Localised Strings, specifying a String with optional Language and Script attributes.
* Formatted Strings, specifying a Localised String with a `format` attribute, in order to admit markup into Strings (whether XML-based or not).

.Basic Document model: Data Types
[plantuml]
....
include::basicdoc_uml/DataTypes.wsd[]
....


[[contributionelementmetadata]]
==== Contribution Element Metadata

In addition to the Basic Data Values, the _Basic Document_ model defines a container encoding the contribution made by a party towards a particular element in the document, with the following attributes:

`dateTime`:: The date and time when the contribution was made.
`contributor`:: The party who made the contribution, as described through the `contributor` element in <<relaton>>.
`inegrityValue`:: A digital signature of the contribution, consisting of a `hash` value and a `signature`, with an associated `publicKey`.

.Basic Document model: Contribution Element Metadata
[plantuml]
....
include::basicdoc_uml/ContribMetadata.wsd[]
....

[[standardsdoc]]
== Standards Document Model

[[standardsdocument]]
=== Document

The _Standards Document_ model extends the _Basic Document_ modelling of the document by requiring the following specific types of section:

* Zero or more optional _prefaces_ (Standard Hierarchical Sections: <<standardssection>>).
* One or more _sections_ (Standard Hierarchical Sections).
* Zero or more _annexes_ (Standard Hierarchical Sections).
* Zero or more _bibliographies_ (Standard References Sections: <<standardsreferencessection>>).

.Standards Document model: Document
[plantuml]
....
include::standoc_uml/StandardDoc_StandardDocument.wsd[]
....

[[standardssection]]
=== Section

The _Standards Document_ model extends the _Basic Document_ modelling of sections by specialising the Basic Section class as follows:

* All sections in a _Standards Document_ model are instances of the Standard Section class, which is a subclass of Basic Section.
* The Standard Section class indicates its status as normative or informative explicitly, through the `status` attribute. (This attribute has been added because it is overtly specified in <<isoiecdir2>>, but the normative status of individual sections in a standard is pertinent to any standards document.)
* Sections in a standards document fall into two categories: Clause Sections, which are numbered, and form part of the main flow of the document, and Content sections (Standard Hierarchical Sections), which are optionally not numbered, and which lie outside the main flow of the document.
* The subclauses of Clauses are themselves Clause Sections; they continue the hierarchical numbering of Clause Sections at deeper hierarchical levels. The subclauses of Content sections are Standard Sections, and need not be numbered.
* Annexes and Clause Sections are modelled in the same way in the _Standards Document_ model. However they are expected to be numbered differently, and to be rendered as separate sequences.

Although it is different to capture in a container-based model, the _Standards Document_ model requires "hanging paragraphs" to be avoided: a Clause section in particular should contain either blocks or subsections, but not both. This is a requirement in <<isoiecdir2>>, but the need to reference text in clauses unambiguously by clause number makes the avoidance of hanging paragraphs desirable for standards documents in general. The requirement is less pressing for Content sections (which are unnumbered), and Annexes (as exemplified in <<isoiecdir2>> itself.)

.Standards Document model: Section
[plantuml]
....
include::standoc_uml/StandardDoc_Sections.wsd[]
....

[[standardsreferencessection]]
=== References Section

Standard References Sections are a subclass of Standard Section. Like the References Sections of the _Basic Document_ model (<<basicsection>>), they are leaf nodes which contain zero or more bibliographical references (as modelled in <<relaton>>).


=== Terms Section and Definition Section

The _Standards Document_ model models two further subclasses of Clause Sections:

* _Definition Sections_ consist of one or more Definition lists (<<basiclist>>), and are used to define symbols and abbreviations used in the remainder of the document. They can also be used as glossaries, with simple definitions, in contrast to the more elaborate definitions given in Terms Sections.
* _Terms Sections_ give elaborated definitions of terms used in the document; they are intended to align to the structure of terms in <<isoiecdir2>>. Term Sections consist of zero or more Terms; _Terms_ in turn are composed of the following elements:

`id`:: An optional identifier for the term, to be used in cross-references.
`preferred`:: One or more names under which the term being defined is canonically known.
`admitted`:: Zero or more names which are acceptable synonyms for the term being defined.
`deprecates`:: Zero or more names which are deprecated synonyms for the term being defined.
`domain`:: An optional semantic domain for the term being defined, in case the term is ambiguous between several semantic domains.
`definition`:: The definition of the term applied in the current document.
`note`:: Zero or more notes about the term.
`example``:: Zero or more examples of how the term is to be used.
`source`:: Zero or more bibliographical sources for the term. These include the `origin` of the term, which is its bibliographical citation (as defined in <<relaton>>); the `status` of the definition (whether _identical_ to the definition given in the origin cited, or _modified_); and, if the definition is modified, a description of the `modification` to the definition applied for this document.

.Standards Document model: Term Section and Definition Section
[plantuml]
....
include::standoc_uml/StandardDoc_Terms.wsd[]
....


[[standardsblock]]
=== Block

There is no difference in the modelling of blocks between the _Basic Document_ model and the _Standards Document_ model.

=== Data Types

There is no difference in the modelling of data types between the _Basic Document_ model and the _Standards Document_ model.

[[isoprofile]]
[appendix]
== ISO Standard Document Model Profile

=== General

The _ISO Standard Document_ model is given here as an exemplar of the application of Metanorma modelling to a particular standard.

[[isodocument]]
=== Document, Section

The _ISO Standard Document_ model extends the _Standards Document_ modelling of the document by requiring the following specific types of section:

* A _Preface_, consisting of a mandatory _Foreword_ (a Basic Section: <<basicsection>>), and an optional _Introduction_ (a ClauseSection: <<standardssection>>, since an ISO Introduction can optionally have numbered subsections).
* One or more Clause Sections (<<standardssection>>).
* Zero or more Annexes (<<standardssection>>).

Annexes in the _ISO Standard Document_ can optionally contain one or more _Appendixes_, which can be thought of as annexes of the annex section.

NOTE: Appendixes are not defined in <<isoiecdir2>>, but they appear in the companion standard <<isoiecdir1>>. For example, Annex SL of <<isoiecdir1>> includes Appendix 1, Appendix 2, and Appendix 3; Appendix 2 "High level structure, identical core text, common terms and core definitions" itself contains an Introduction and 10 clauses, including a Terms clause.

The _ISO Standard Document_ model document also includes zero or more `termSources` elements, giving the citations for the documents that the Terms Section draws on for its definitions and repertoire of terms.

The _ISO Standard Document_ model document uses ISO-specific extensions to the <<relaton>> metadata about a document (<<isobib>>).

.ISO Standard Document model: Document
[plantuml]
....
include::iso_uml/IsoDoc_IsoStandardDocument.wsd[]
....

[[isoblock]]
=== Block

The _ISO Standard Document_ model extends the _Standards Document_ modelling of blocks for one block definition:

* The types that an Admonition can belong to are overridden to belong to the following set prescribed in <<isoiecdir2>>: _Danger, Caution, Warning, Important, Safety Precaution_.

.ISO Standard Document model: Block
[plantuml]
....
include::iso_uml/IsoDoc_IsoBlocks.wsd[]
....

[[isobib]]
=== Bibliography

We note here the _ISO Standard Document_ overrides of the <<relaton>> bibliographic model; although the contents of <<relaton>> are out of scope of this document, its customisation for a specific standard are in scope.

<<relaton>> is intended as a highly generic model, and custom bibliographic elements would impede the reuse of bibliographic entries between standards. However, it is useful for the metadata describing the current document (`bibdata`: <<basicdocument>>) to be enriched to provide metadata relevant to the standard class.

The bibliographic modelling of ISO documents is enriched compared to <<relaton>>  as follows:

* The document identifier is refined to contain three optional parts: a project number, a part number, and a technical committee document number.
* The document title is broken down into an optional Introductory component, a mandatory Main component, and an optional Part component.
* The document type is constrained to be one of the following: _International Standard, Technical Specification, Technical Report, Publicly Available Specification, International Workshop Agreement, Guide_.
* The document status is broken down into an ISO Document Stage code (<<isostage>>), an ISO Document Substage code (<<isostage>>), and an Iteration number.
* The editorial group responsible for the document is defined with four components: a mandatory Technical Committee, an optional Subcommittee, an optional Workgroup, and an optional Secretariat. The Technical Committee, Subcommittee and Workgroup, in turn, are instances of the ISO Subgroup class, defined as having a name, an optional type, and an optional number.
* The document has one or more International Classification for Standards classifications <<ics>>. The ICS classification is defined as a code, and an optional text explaining the code.
* The document has zero or more source URIs.
* The document has an optional abstract.
* The document has an optional "All Parts" boolean attribute, indicating whether the bibliographic description applies across all Part documents under the same project number (which makes it a multi-document description).

.ISO Standard Document model: Bibliography
[plantuml]
....
include::iso_uml/IsoDoc_IsoBibliographicItem.wsd[]
....

[[csdprofile]]
[appendix]
== CSD Standard Document Model Profile

=== General

The _CSD Standard Document_ model is given here as an exemplar of the application of Metanorma modelling to a particular standard (standards published by the Calendaring and Scheduling Consortium).

=== Document, Section

The _CSD Standard Document_ model extends the _Standards Document_ modelling of the document by requiring the following specific types of section:

* An optional _Foreword_ (a Standards Hierarchical Section: <<standardssection>>).
* An optional _Introduction_ (a Standards Hierarchical Section: <<standardssection>>).
* One or more Clause Sections (<<standardssection>>).
* Zero or more Annexes (<<standardssection>>).

[[csdblock]]
=== Block

The _CSD Standard Document_ model extends the _Standards Document_ modelling of blocks for one block definition:

* The definition of Figure is altered to allow Ascii art as an option for its content, as a string (`pre`). As with Sourcecode (<<basicsourcecode>>), the string should be treated as preformatted text, with whitespace treated as significant.

=== Inline Elements

The _CSD Standard Document_ model extends the _Standards Document_ modelling of inline elements by one element:

* The `keyword` element is added as a subclass of Text Element (<<textelements>>). The element is used to represent code keywords, as with `code` in HTML, and should be rendered in monospace.

=== Bibliography

The provisos which apply to ISO bibliographic entries (<<isobib>>) also apply here.

The bibliographic modelling of CSD documents is enriched compared to <<relaton>> as follows:

* The document type is constrained to be one of the following: _Code, Presentation, Proposal, Standard, Report_.
* The document status is constrained to be one of the following: _Proposal, Working Draft, Committee Draft, Final Draft, Published, Withdrawn_.
* The editorial group responsible for the document is defined with a single components: a mandatory Technical Committee. The Technical Committee has a type of either _Technical_ or _Provisional_.

.CSD Standard Document model
[plantuml]
....
include::csd_uml/Csd_StandardDocument.wsd[]
....

[bibliography]
== Bibliography

* [[[isoiecdir1,ISO/IEC DIR 1]]], _Procedures for the technical work_

* [[[isoiecdir2-2004,ISO/IEC DIR 2:2004]]], _Principles and rules for the structure and drafting of ISO and IEC documents_

* [[[isoiecdir2,ISO/IEC DIR 2:2018]]], _Principles and rules for the structure and drafting of ISO and IEC documents_

* [[[iso690,ISO 690]]], _Information and documentation -- Guidelines for bibliographic references and citations to information resources_

* [[[iso5127,ISO 5127:2017]]], _Information and documentation — Foundation and vocabulary_

* [[[gbt11,CN(GB/T 1.1-2009)]]], 标准化工作导则 第1部分：标准的结构和编写 (_Directives for standardization. Part 1: The structure and drafting of standards_)

* [[[rfc7749,IETF RFC 7749]]], _The "xml2rfc" Version 2 Vocabulary_

* [[[rfc7991,IETF RFC 7991]]], _The "xml2rfc" Version 3 Vocabulary_

* [[[asciidoctor,8]]] _Asciidoctor User Manual._ https://asciidoctor.org/docs/user-manual/

* [[[ics,9]]] _ISO International Classification for Standards (ICS)_, https://www.iso.org/publication/PUB100033.html

* [[[isostage,10]]] _International harmonized stage codes_, https://www.iso.org/stage-codes.html

* [[[IEV,IEV]]], _IEV_
