= Metanorma
:technical-committee-number: 46
:docnumber: XXXXX
:tc-document-number: 9999
:edition: 1
:ref-docnumber: ISO XXXXX:2018(E)
:copyright-year: 2018
:language: en
:title-intro-en: Information and documentation
:title-main-en: Standards reference model and serialization
:title-intro-fr: Information et documentation
:title-main-fr: Modèle de référence bibliographique et sérialisation
:doctype: international-standard
:docstage: 10
:docsubstage: 92
:technical-committee-type: TC
:technical-committee-number: 46
:technical-committee: Information and documentation
:subcommittee-type: SC
:subcommittee-number: 9
:subcommittee: Identification and description
:workgroup-type: WG
:workgroup-number: 15
:workgroup: Bibliography
:secretariat: ANSI
:language: en
:script: Latn
:draft:
:toc:
:stem:
:xrefstyle: short

[[foreword]]
.Foreword
ISO (the International Organization for Standardization)
is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

The procedures used to develop this document and those intended for its further maintenance are described in the ISO/IEC Directives, Part 1. In particular the different approval criteria needed for the different types of ISO documents should be noted. This document was drafted in accordance with the editorial rules of the ISO/IEC Directives, Part 2 (see www.iso.org/directives).

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights. Details of any patent rights identified during the development of the document will be in the Introduction and/or on the ISO list of patent declarations received (see www.iso.org/patents).

Any trade name used in this document is information given for the convenience of users and does not constitute an endorsement.

For an explanation on the voluntary nature of standards, the meaning of ISO specific terms and expressions related to conformity assessment, as well as information about ISO's adherence to the World Trade Organization (WTO) principles in the Technical Barriers to Trade (TBT) see the following URL: www.iso.org/iso/foreword.html.

This document was prepared by Technical Committee ISO/TC {technical-committee-number}, _{technical-committee}_.

This is the first edition of this document.

[[introduction]]
  
:sectnums!:
== Introduction

The process of generating standards documents is problematic, and becoming more so with the increased work burden on standards organisations. ISO is no exception to this issue, and concerns have been raised over both the efficiency and the effectiveness of the workflows around generating standards in those bodies and elsewhere. 

* The rigorous and detailed directives around document structure articulated in <<isoiecdir2>> are being manually validated by the editorial teams, with mixed results.
* Editing of documents substantially revolves around Microsoft Word toolsets, with all the problems that conflating document structure and presentation introduce. The editorial process has to spend significant amounts of time on formatting rather than document content, and is vulnerable to error. Opportunities to automate document presentation independently of content (as is routinely done in the HTML world with CSS) are not being taken up.
* Existing exchange mechanisms for documents have been claimed to focus on document appearance, rather than document structure, and so do not alleviate the formatting burden on the editorial process.
* Different standards have completely different workflows, with different inputs: anyone submitting standards text to more than one standard body has to replicate a significant amount of work.
* Within the ISO community, subcommittees are resorting to extreme measures such as always having a national body put in a negative vote in DIS or DAM ballots, in order to force a text review, and to reduce the large number of content and formatting errors that routinely occur in published standards.

These problems are if anything even more acute in other standards bodies. The Chinese National Standards body's counterpart to <<isoiecdir2>>, <<gbt11>>, is rather more prescriptive than <<isoiecdir2>> about formatting; despite support of standards authoring through an exhaustive Microsoft Word template wizard, the adherence of published standards to <<gbt11>> is haphazard at best. The wizard provided by GB was a Windows-specific tool that no longer works on contemporary systems -- which highlights another vulnerability with using proprietary tools to support standards production.

We have identified a need for a standards document production process that leverages a non-WYSIWYG approach to document production, such as has been used for years in instances like LaTeX, HTML, and DocBook, and more recently Markdown and Asciidoctor. We have also identified a need for the process to be based on a formal document model,  such as is seen in DocBook, HTML, and TEI, and able to deal with the particular needs of standards documents.

In this document, we propose Metanorma as such a standards document production process. The process centers around the Metanorma document model, which is intended to encompass the core similarities between standards bodies' versions of standards documents; particularities of different standards bodies are kept to a minimum, and expressed as local extensions. The process generates a semantic representation of the standards document expressed in the abstract document model, based on non-WYSIWYG, lightly marked-up text-based input. A further step then generates different output formats from the same document model expression, treating them as the application of styling rather than as document editing.

This approach has the following benefits:

* The approach enables an end-to-end, author-to-publishing workflow, with well-managed artefacts along each stage, that editorial bodies can exercise appropriate control over. This becomes all the easier as each artefact until the very end is text rather than binary. 
* Much of the tedium and unpredictability around formatting documents to align with presentation requirements is automated, since the document model is semantic, and abstracted away from presentation. Formatting is applied only at the very end of the process. This includes not only formatting details such as margin sizes and font choices, but also autonumbering of sections and tables, cross-referencing, automated generation of references, and generating tables of contents.
* The structural and content requirements around standards documents can be captured in the document model, and documents can therefore be subject to formal validation against the model. That means that a Metanorma-based process can provide substantial feedback to authors on the extent to which they comply with the rules expressed in specifications like <<isoiecdir2>> -- including rules around wording (e.g. where requirements can occur), as well as document structure.
* The document model is substantially the same across standards, as is the non-WYSIWYG text input it is derived from. That means that text can be repurposed for different standards bodies with minimal effort: it is treated mostly as a swap-out of stylesheets, with only minor adjustments needed to content.

Currently the Metanorma process is realised in the Ruby programming language, with the non-WYSIWYG text input expressed in Asciidoc, and output generated in
HTML, Microsoft Word (.doc), and PDF (generated from HTML). Because of the modular approach taken to the toolset, other input and output formats can be supported.

Development of Metanorma started in late 2017. Metanorma is already in used by standards authors for several standards:

* Draft submissions to ISO (all types: standards, guides, PAS, TR, TS...)
* CalConnect Standards (as its official format)
* IETF RFCs and Internet-Drafts (among official authoring methods)
* Chinese National Standards ("GB standards") (for draft submission)
* Cloud Security Alliance Documents (workgroup outputs)


== Scope

This document provides the Metanorma reference model and serialisation for standards documents.

The mapping of the reference model to output formats such as HTML, and the application of organisation-specific styling to those outputs, is out of scope of this document.

Markup conventions in text markup schemes (such as Asciidoc) that enable generation of the reference model are out of scope of this document.

[bibliography]
== Normative References

The following documents are referred to in the text in such a way that some or
all of their content constitutes requirements of this document. For dated
references, only the edition cited applies. For undated references, the latest
edition of the referenced document (including any amendments) applies.

* [[[isoiecdir2,ISO/IEC DIR 2]]], _Principles and rules for the structure and drafting of ISO and IEC documents_

* [[[gbt11,GB/T 1.1]]], 标准化工作导则 第1部分：标准的结构和编写 (_Directives for standardization. Part 1: The structure and drafting of standards_)

== Terms and Definitions

== Modelling Hierarchy



