= Metanorma
:technical-committee-number: 46
:docnumber: XXXXX
:tc-document-number: 9999
:edition: 1
:ref-docnumber: ISO XXXXX:2018(E)
:copyright-year: 2018
:language: en
:title-intro-en: Information and documentation
:title-main-en: Standards reference model and serialization
:title-intro-fr: Information et documentation
:title-main-fr: ****
:doctype: international-standard
:docstage: 10
:docsubstage: 92
:technical-committee-type: TC
:technical-committee-number: 46
:technical-committee: Information and documentation
:subcommittee-type: SC
:subcommittee-number: 9
:subcommittee: Identification and description
:workgroup-type: WG
:workgroup-number: 15
:workgroup: Bibliography
:secretariat: ANSI
:language: en
:script: Latn
:draft:
:toc:
:stem:
:xrefstyle: short

[[foreword]]
.Foreword
ISO (the International Organization for Standardization)
is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

The procedures used to develop this document and those intended for its further maintenance are described in the ISO/IEC Directives, Part 1. In particular the different approval criteria needed for the different types of ISO documents should be noted. This document was drafted in accordance with the editorial rules of the ISO/IEC Directives, Part 2 (see www.iso.org/directives).

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights. Details of any patent rights identified during the development of the document will be in the Introduction and/or on the ISO list of patent declarations received (see www.iso.org/patents).

Any trade name used in this document is information given for the convenience of users and does not constitute an endorsement.

For an explanation on the voluntary nature of standards, the meaning of ISO specific terms and expressions related to conformity assessment, as well as information about ISO's adherence to the World Trade Organization (WTO) principles in the Technical Barriers to Trade (TBT) see the following URL: www.iso.org/iso/foreword.html.

This document was prepared by Technical Committee ISO/TC {technical-committee-number}, _{technical-committee}_.

This is the first edition of this document.

[[introduction]]
  
:sectnums!:
== Introduction

The process of generating standards documents is problematic, and becoming more so with the increased work burden on standards organisations. ISO is no exception to this issue, and concerns have been raised over both the efficiency and the effectiveness of the workflows around generating standards in those bodies and elsewhere. 

* The rigorous and detailed directives around document structure articulated in <<isoiecdir2>> are being manually validated by the editorial teams, with mixed results.
* Editing of documents substantially revolves around Microsoft Word toolsets, with all the problems that conflating document structure and presentation introduce. The editorial process has to spend significant amounts of time on formatting rather than document content, and is vulnerable to error. Opportunities to automate document presentation independently of content (as is routinely done in the HTML world with CSS) are not being taken up.
* Existing exchange mechanisms for documents have been claimed to focus on document appearance, rather than document structure, and so do not alleviate the formatting burden on the editorial process.
* Different standards have completely different workflows, with different inputs: anyone submitting the same standards text to more than one standard body has to replicate a significant amount of work.
* Within the ISO community, subcommittees are resorting to extreme measures such as always having a national body put in a negative vote in DIS or DAM ballots, in order to force a text review, and to reduce the large number of content and formatting errors that routinely occur in published standards.

These problems are if anything even more acute in other standards bodies. The Chinese National Standards body's counterpart to <<isoiecdir2>>, <<gbt11>>, is rather more prescriptive than <<isoiecdir2>> about formatting; despite support of standards authoring through an exhaustive Microsoft Word template wizard, the adherence of published standards to <<gbt11>> is haphazard at best. The wizard provided by the Chinese National Standards body was a Windows-specific tool written in 2010 that no longer works on contemporary systems -- which highlights another vulnerability with using proprietary tools to support standards production.

We have identified a need for a standards document production process that leverages a non-WYSIWYG approach to document production, such as has been used for years in instances like LaTeX, HTML, and DocBook, and more recently Markdown and Asciidoctor. We have also identified a need for the process to be based on a formal document model,  such as is seen in DocBook, HTML, and TEI, and able to deal with the particular needs of standards documents.

In this document, we propose Metanorma as such a standards document production process. The process centers around the Metanorma document model, which is intended to encompass the core similarities between standards bodies' versions of standards documents; particularities of different standards bodies are kept to a minimum, and expressed as local extensions. The process generates a semantic representation of the standards document expressed in the abstract document model, based on non-WYSIWYG, lightly marked-up text-based input. A further step then generates different output formats from the same document model expression, treating them as the application of styling rather than as document editing.

This approach has the following benefits:

* The approach enables an end-to-end, author-to-publishing workflow, with well-managed artefacts along each stage, that editorial bodies can exercise appropriate control over. This becomes all the easier as each artefact until the very end is text rather than binary: that allows the document management infrastructure around computer source code (such as version control) to be used to manage standards document production. 
* Much of the tedium and unpredictability around formatting documents to align with presentation requirements is automated, since the document model is semantic, and abstracted away from presentation. Formatting is applied only at the very end of the process. This includes not only formatting details such as margin sizes and font choices, but also autonumbering of sections and tables, cross-referencing, automated generation of references, and generating tables of contents.
* The structural and content requirements around standards documents can be captured in the document model, and documents can therefore be subject to formal validation against the model. That means that a Metanorma-based process can provide substantial feedback to authors on the extent to which they comply with the rules expressed in specifications like <<isoiecdir2>> -- including rules around wording (e.g. where requirements can occur), as well as document structure.
* The document model is substantially the same across standards, as is the non-WYSIWYG text input that it is derived from. That means that text can be repurposed for different standards bodies with minimal effort: it is treated mostly as a swap-out of stylesheets, with only minor adjustments needed to content.

Currently the Metanorma process is realised in the Ruby programming language, with the non-WYSIWYG text input expressed in Asciidoc, and output generated in
HTML, Microsoft Word (.doc), and PDF (generated from HTML). Because of the modular approach taken to the toolset, other input and output formats can be supported.

Development of Metanorma started in late 2017. Metanorma is already in used by standards authors for several standards:

* Draft submissions to ISO (all types: standards, guides, PAS, TR, TS...)
* CalConnect Standards (as its official format)
* IETF RFCs and Internet-Drafts (among official authoring methods)
* Chinese National Standards ("GB standards") (for draft submission)
* Cloud Security Alliance Documents (workgroup outputs)


== Scope

This document provides the Metanorma reference model for standards documents. Serialisation of the reference model will be discussed in a separate document.

The mapping of the reference model to output formats such as HTML, and the application of organisation-specific styling to those outputs, is out of scope of this document.

This document discusses processes around customising the reference model for different standards, and describes customisation for ISO standards as one example profile in <<isoprofile>>. Prescribing profiles of the document model for particular standards, however, is out of scope of this document.

The modelling of bibliographies and bibliographic citations is part of the reference model, but is the subject of a separate proposal, <<relaton>>, and is not discussed in detail in this document.

The modelling of changes to documents is in scope of the Basic Document model described here, but is not described in this document.

Markup conventions in text markup schemes (such as Asciidoc) that enable generation of the reference model are out of scope of this document.

[bibliography]
== Normative References

// Surely the following boilerplate can be suppressed

// All of these I'd argue are informative not normative

The following documents are referred to in the text in such a way that some or
all of their content constitutes requirements of this document. For dated
references, only the edition cited applies. For undated references, the latest
edition of the referenced document (including any amendments) applies.

* [[[isoiecdir2,ISO/IEC DIR 2]]], _Principles and rules for the structure and drafting of ISO and IEC documents_

* [[[iso690,ISO 690]]], _Information and documentation -- Guidelines for bibliographic references and citations to information resources_

* [[[gbt11,CN(GB/T 1.1)]]], 标准化工作导则 第1部分：标准的结构和编写 (_Directives for standardization. Part 1: The structure and drafting of standards_)

* [[[relaton,ISO xxxx:--]]] footnote:[In draft], _Information and documentation -- Bibliographic reference model and serialization_

* [[[rfc7749,IETF RFC 7749]]], _The "xml2rfc" Version 2 Vocabulary_

* [[[rfc7991,IETF RFC 7991]]], _The "xml2rfc" Version 3 Vocabulary_

* [[[asciidoctor,Asciidoctor]]], _Asciidoctor User Manual._ https://asciidoctor.org/docs/user-manual/


== Terms and Definitions

== Modelling

=== Structure

The Metanorma document model is expressed hierarchically. 

* At its base is a _Basic Document_ model, which expresses the structure of generic documents.
* The Basic Document model is specialised as a _Standards Document_ structure, conveying the structure particular to standards documents as a class.
* The Standards Document model is further specialised into models specific to particular standards. 
* Specific standards models can form the basis in turn of other standards models. For example, the Chinese National Standards model, as described in <<gbt11>>, is structurally modelled after ISO documents, and is explicitly described as a localisation of the 2004 version of <<isoiecdir2>>. So the Chinese Standards model is best expressed as a specialisation of the ISO Standards model.

Specialisation of a model consists of:

* Adding classes to a base model.
* Changing attributes of a base model class. This is not restricted to adding attributes, as is the case in typical entity subclassing; it can also include removing attributes from a class, changing their obligation and cardinality, and changing their type, including changing enumerations. Attributes can be overruled at any level; for example, standards-specific models routinely enhance the bibliographic model at the base of the hierarchy.
* For reasons of clarity, renaming classes and attributes is avoided in specialisation.

The classes involved in the document model are of three classes:

* Sections
* Blocks (paragraph-level groupings of text)
* Inline elements (groupings of text smaller than a paragraph, including plain strings)

In the Metanorma model, the classes are in a strict hierarchical relation: documents consist of sections, which consist of blocks, which consist of inline elements. Sections can be nested within sections (e.g. clauses and subclauses); blocks can be nested within blocks (e.g. nested lists). Although the model does not currently provide for it, inline elements can also be embedded within other inline elements (e.g. bold + italics). However, sections are not expected to be siblings of blocks, nor blocks of inline elements. For example, a list (block) is not expected to occur next to inline text within a paragraph. For that reason, paragraphs cannot contain other block elements, such as lists or tables.

NOTE: This constraint is inherited from tools like Markdown and Asciidoctor, and is not present in XML-based schemas like HTML, TEI-C, or DocBook. It helps to simplify the document model significantly, and while it sacrifices some expressive potential, the difference is minor, particularly with regards to the rendering of paragraphs. 

The Basic Document model contains the bulk of the blocks and inline elements in the Metanorma model. The Standards Model and the standard-specific models mostly deal with the organisation of sections within a standards document.

The Metanorma document model depends on the <<iso690>> bibliography model for its expression of bibliographic references. The specific model instantiation and serialisation it uses is the subject of a separate proposal, <<relaton>>, and is not discussed further here.

=== Influences

The Metanorma document model has drawn on several existing models, with a view to reflecting the expressiveness of existing standards, but also to align with the capability of established document production tools.

The standards models consulted most closely for Metanorma are those for ISO standards <<isoiecdir2>> and RFC standards (<<rfc7749>>, <<rfc7991>>). The document production tools that Metanorma consciously sought to align with are HTML 4, HTML 5, Markdown, Asciidoctor (<<Asciidoctor>>), and Microsoft Word. The modelling of blocks and inline elements in particular are closely aligned with HTML.

== Basic Document Model

=== Document

The _Basic Document_ model treats all documents as collections of _sections_ (<<basicsection>>). It also adds the following metadata as part of the document model:

// Please confirm what I've assumed here for identifier

`identifier`:: a globally unique identifier for the document in an agreed identifier schema. The identifier is to be used for tracking interactions with the document without depending on formal document registries; it would be exemplified by a GUID, rather than a document registry identifier such as "ISO 639", which belongs to `bibdata`.
`bibdata`:: a bibliographic description, capturing bibliographic metadata about the document itself, including authors, title, and date of production (<<relaton>>)
`version`:: information about the current version of the document, including an `edition` (represented in the Basic model as an ordinal numeral), the date of latest revision (`revisionDate`), and a textual description of the current `draft`.
`integrityValue`:: an optional digital signature of the document (<<integrityValue>>). 

[plantuml]
....
include::basicdoc_uml/BasicDocument.wsd[]
....

[[basicsection]]
=== Section


[[datavalues]]
=== Data Values

[[integrityvalue]]
==== Integrity Value


== Standards Document Model

TODO: UML diagram


[[isoprofile]]
[appendix]
== ISO Standard Document Model Profile

The ISO Standard document model is given here as an exemplar of the application of Metanorma modelling to a particular standard

TODO: UML diagram

TODO: Grammar

[bibliography]
== Bibliography 

