= Metanorma
:technical-committee-number: 46
:docnumber: XXXXX
:tc-document-number: 9999
:edition: 1
:ref-docnumber: ISO XXXXX:2018(E)
:copyright-year: 2018
:language: en
:title-intro-en: Information and documentation
:title-main-en: Standards reference model and serialization
:title-intro-fr: Information et documentation
:title-main-fr: ****
:doctype: international-standard
:docstage: 10
:docsubstage: 92
:technical-committee-type: TC
:technical-committee-number: 46
:technical-committee: Information and documentation
:subcommittee-type: SC
:subcommittee-number: 9
:subcommittee: Identification and description
:workgroup-type: WG
:workgroup-number: 15
:workgroup: Bibliography
:secretariat: ANSI
:language: en
:script: Latn
:draft:
:toc:
:stem:
:xrefstyle: short

[[foreword]]
.Foreword
ISO (the International Organization for Standardization)
is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

The procedures used to develop this document and those intended for its further maintenance are described in the ISO/IEC Directives, Part 1. In particular the different approval criteria needed for the different types of ISO documents should be noted. This document was drafted in accordance with the editorial rules of the ISO/IEC Directives, Part 2 (see www.iso.org/directives).

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights. Details of any patent rights identified during the development of the document will be in the Introduction and/or on the ISO list of patent declarations received (see www.iso.org/patents).

Any trade name used in this document is information given for the convenience of users and does not constitute an endorsement.

For an explanation on the voluntary nature of standards, the meaning of ISO specific terms and expressions related to conformity assessment, as well as information about ISO's adherence to the World Trade Organization (WTO) principles in the Technical Barriers to Trade (TBT) see the following URL: www.iso.org/iso/foreword.html.

This document was prepared by Technical Committee ISO/TC {technical-committee-number}, _{technical-committee}_.

This is the first edition of this document.

[[introduction]]
  
:sectnums!:
== Introduction

The process of generating standards documents is problematic, and becoming more so with the increased work burden on standards organisations. ISO is no exception to this issue, and concerns have been raised over both the efficiency and the effectiveness of the workflows around generating standards in those bodies and elsewhere. 

* The rigorous and detailed directives around document structure articulated in <<isoiecdir2>> are being manually validated by the editorial teams, with mixed results.
* Editing of documents substantially revolves around Microsoft Word toolsets, with all the problems that conflating document structure and presentation introduce. The editorial process has to spend significant amounts of time on formatting rather than document content, and is vulnerable to error. Opportunities to automate document presentation independently of content (as is routinely done in the HTML world with CSS) are not being taken up.
* Existing exchange mechanisms for documents have been claimed to focus on document appearance, rather than document structure, and so do not alleviate the formatting burden on the editorial process.
* Different standards have completely different workflows, with different inputs: anyone submitting the same standards text to more than one standard body has to replicate a significant amount of work.
* Within the ISO community, subcommittees are resorting to extreme measures such as always having a national body put in a negative vote in DIS or DAM ballots, in order to force a text review, and to reduce the large number of content and formatting errors that routinely occur in published standards.

These problems are if anything even more acute in other standards bodies. The Chinese National Standards body's counterpart to <<isoiecdir2>>, <<gbt11>>, is rather more prescriptive than <<isoiecdir2>> about formatting; despite support of standards authoring through an exhaustive Microsoft Word template wizard, the adherence of published standards to <<gbt11>> is haphazard at best. The wizard provided by the Chinese National Standards body was a Windows-specific tool written in 2010 that no longer works on contemporary systems -- which highlights another vulnerability with using proprietary tools to support standards production.

We have identified a need for a standards document production process that leverages a non-WYSIWYG approach to document production, such as has been used for years in instances like LaTeX, HTML, and DocBook, and more recently Markdown and Asciidoctor. We have also identified a need for the process to be based on a formal document model,  such as is seen in DocBook, HTML, and TEI, and able to deal with the particular needs of standards documents.

In this document, we propose Metanorma as such a standards document production process. The process centers around the Metanorma document model, which is intended to encompass the core similarities between standards bodies' versions of standards documents; particularities of different standards bodies are kept to a minimum, and expressed as local extensions. The process generates a semantic representation of the standards document expressed in the abstract document model, based on non-WYSIWYG, lightly marked-up text-based input. A further step then generates different output formats from the same document model expression, treating them as the application of styling rather than as document editing.

This approach has the following benefits:

* The approach enables an end-to-end, author-to-publishing workflow, with well-managed artefacts along each stage, that editorial bodies can exercise appropriate control over. This becomes all the easier as each artefact until the very end is text rather than binary: that allows the document management infrastructure around computer source code (such as version control) to be used to manage standards document production. 
* Much of the tedium and unpredictability around formatting documents to align with presentation requirements is automated, since the document model is semantic, and abstracted away from presentation. Formatting is applied only at the very end of the process. This includes not only formatting details such as margin sizes and font choices, but also autonumbering of sections and tables, cross-referencing, automated generation of references, and generating tables of contents.
* The structural and content requirements around standards documents can be captured in the document model, and documents can therefore be subject to formal validation against the model. That means that a Metanorma-based process can provide substantial feedback to authors on the extent to which they comply with the rules expressed in specifications like <<isoiecdir2>> -- including rules around wording (e.g. where requirements can occur), as well as document structure.
* The document model is substantially the same across standards, as is the non-WYSIWYG text input that it is derived from. That means that text can be repurposed for different standards bodies with minimal effort: it is treated mostly as a swap-out of stylesheets, with only minor adjustments needed to content.

Currently the Metanorma process is realised in the Ruby programming language, with the non-WYSIWYG text input expressed in Asciidoc, and output generated in
HTML, Microsoft Word (.doc), and PDF (generated from HTML). Because of the modular approach taken to the toolset, other input and output formats can be supported.

Development of Metanorma started in late 2017. Metanorma is already in used by standards authors for several standards:

* Draft submissions to ISO (all types: standards, guides, PAS, TR, TS...)
* CalConnect Standards (as its official format)
* IETF RFCs and Internet-Drafts (among official authoring methods)
* Chinese National Standards ("GB standards") (for draft submission)
* Cloud Security Alliance Documents (workgroup outputs)


== Scope

This document provides the Metanorma reference model for standards documents. Serialisation of the reference model will be discussed in a separate document.

The mapping of the reference model to output formats such as HTML, and the application of organisation-specific styling to those outputs, is out of scope of this document.

This document discusses processes around customising the reference model for different standards, and describes customisation for ISO standards as one example profile in <<isoprofile>>. Prescribing profiles of the document model for particular standards, however, is out of scope of this document.

The modelling of bibliographies and bibliographic citations is part of the reference model, but is the subject of a separate proposal, <<relaton>>, and is not discussed in detail in this document.

The modelling of changes to documents is in scope of the Basic Document model described here, but is not described in this document.

Markup conventions in text markup schemes (such as Asciidoc) that enable generation of the reference model are out of scope of this document.

[bibliography]
== Normative References

// Surely the following boilerplate can be suppressed

// All of these I'd argue are informative not normative

The following documents are referred to in the text in such a way that some or
all of their content constitutes requirements of this document. For dated
references, only the edition cited applies. For undated references, the latest
edition of the referenced document (including any amendments) applies.

* [[[isoiecdir2,ISO/IEC DIR 2]]], _Principles and rules for the structure and drafting of ISO and IEC documents_

* [[[iso690,ISO 690]]], _Information and documentation -- Guidelines for bibliographic references and citations to information resources_

* [[[gbt11,CN(GB/T 1.1)]]], 标准化工作导则 第1部分：标准的结构和编写 (_Directives for standardization. Part 1: The structure and drafting of standards_)

* [[[relaton,ISO xxxx:--]]] footnote:[In draft], _Information and documentation -- Bibliographic reference model and serialization_

* [[[rfc7749,IETF RFC 7749]]], _The "xml2rfc" Version 2 Vocabulary_

* [[[rfc7991,IETF RFC 7991]]], _The "xml2rfc" Version 3 Vocabulary_

* [[[asciidoctor,Asciidoctor]]], _Asciidoctor User Manual._ https://asciidoctor.org/docs/user-manual/


== Terms and Definitions

== Modelling

=== Structure

The Metanorma document model is expressed hierarchically. 

* At its base is a _Basic Document_ model, which expresses the structure of generic documents.
* The Basic Document model is specialised as a _Standards Document_ structure, conveying the structure particular to standards documents as a class.
* The Standards Document model is further specialised into models specific to particular standards. 
* Specific standards models can form the basis in turn of other standards models. For example, the Chinese National Standards model, as described in <<gbt11>>, is structurally modelled after ISO documents, and is explicitly described as a localisation of the 2004 version of <<isoiecdir2>>. So the Chinese Standards model is best expressed as a specialisation of the ISO Standards model.

Specialisation of a model consists of:

* Adding classes to a base model.
* Changing attributes of a base model class. This is not restricted to adding attributes, as is the case in typical entity subclassing; it can also include removing attributes from a class, changing their obligation and cardinality, and changing their type, including changing enumerations. Attributes can be overruled at any level; for example, standards-specific models routinely enhance the bibliographic model at the base of the hierarchy.
* For reasons of clarity, renaming classes and attributes is avoided in specialisation.

The classes involved in the document model are of three classes:

* Sections (<<basicsection>>, <<standardssection>>)
* Blocks (paragraph-level groupings of text) (<<basicblock>>, <<standardsblock>>)
* Inline elements (groupings of text smaller than a paragraph, including plain strings) (<<inline>>)

In the Metanorma model, the classes are in a strict hierarchical relation: documents consist of sections, which consist of blocks, which consist of inline elements. Sections can be nested within sections (e.g. clauses and subclauses); blocks can be nested within blocks (e.g. nested lists). Although the model does not currently provide for it, inline elements can also be embedded within other inline elements (e.g. bold + italics). However, sections are not expected to be siblings of blocks, nor blocks of inline elements. For example, a list (block) is not expected to occur next to inline text within a paragraph. For that reason, paragraphs cannot contain other block elements, such as lists or tables.

NOTE: This constraint is inherited from tools like Markdown and Asciidoctor, and is not present in XML-based schemas like HTML, TEI-C, or DocBook. It helps to simplify the document model significantly, and while it sacrifices some expressive potential, the difference is minor, particularly with regards to the rendering of paragraphs. 

The Basic Document model contains the bulk of the blocks and inline elements in the Metanorma model. The Standards Model and the standard-specific models mostly deal with the organisation of sections within a standards document.

The Metanorma document model depends on the <<iso690>> bibliography model for its expression of bibliographic references. The specific model instantiation and serialisation it uses is the subject of a separate proposal, <<relaton>>, and is not discussed further here.

=== Influences

The Metanorma document model has drawn on several existing models, with a view to reflecting the expressiveness of existing standards, but also to align with the capability of established document production tools.

The standards models consulted most closely for Metanorma are those for ISO standards <<isoiecdir2>> and RFC standards (<<rfc7749>>, <<rfc7991>>). The document production tools that Metanorma consciously sought to align with are HTML 4, HTML 5, Markdown, Asciidoctor (<<Asciidoctor>>), and Microsoft Word. The modelling of blocks and inline elements in particular are closely aligned with HTML.

== Basic Document Model

[[basicdocument]]
=== Document

The _Basic Document_ model treats all documents as collections of _sections_ (<<basicsection>>). It also adds the following metadata as part of the document model:

// Please confirm what I've assumed here for identifier

`identifier`:: a globally unique identifier for the document in an agreed identifier schema. The identifier is to be used for tracking interactions with the document without depending on formal document registries; it would be exemplified by a GUID, rather than a document registry identifier such as "ISO 639", which belongs to `bibdata`.
`bibdata`:: a bibliographic description, capturing bibliographic metadata about the document itself, including authors, title, and date of production (<<relaton>>)
`version`:: information about the current version of the document, including an `edition` (represented in the Basic model as an ordinal numeral), the date of latest revision (`revisionDate`), and a textual description of the current `draft`.
`integrityValue`:: an optional digital signature of the document (<<integrityValue>>). 

[plantuml]
....
include::basicdoc_uml/BasicDocument.wsd[]
....

[[basicsection]]
=== Section

The _Basic Document_ model is generic in its application, and accordingly does not do detailed modelling of the differences between sections; that is deferred for the _Standards Document_ model. The Basic model only recognises the following classes of section:

* _Basic Sections_, which are leaf nodes (do not contain any sections).
* _Hierarchical Sections_, which can contain other sections. Hierarchical Sections are modelled as a subclass of Basic Sections, so the hierarchical arrangement of sections can be arbitrarily deep. 
* _Content Sections_, which in the Basic model are treated as equivalent to Hierarchical Sections.
* _References Sections_, which are leaf nodes, and contain zero or more bibliographical references (as modelled in <<relaton>>).

All sections are modelled as having the following attributes: 

`title`:: an optional title of the section.
`id`:: an optional identifier for the section, to be used for cross-references.
`blocks`:: zero or more text blocks, containing the textual content of the section (but excluding subsections, which are only present in Hierarchical Sections).
`notes`:: any notes whose scope is the entire section, rather than a specific block. Notes are modelled as a sequence of zero or more paragraphs.


NOTE: In the Basic Document model, a section can contain both blocks of text and subsections; in rendering, the blocks of text are presumed to come before the subsections. The ISO document model proscribes the coocurrence of text and subsections in a clause (= section) as "hanging paragraphs"; that proscription is modelled as an override of the model specific to Standards documents, for which the referencing of clauses is a paramount concern (<<standardsdoc>>).

// TODO: refine reference

[plantuml]
....
include::basicdoc_uml/Sections.wsd[]
....

[[basicblock]]
=== Block

Blocks of text are all modelled as subclasses of the _Basic Block_ class, which has the following attributes common to all blocks:

`id`:: an optional identifier for the block, to be used for cross-references.
`notes`:: any notes whose scope is the block. Notes are modelled as a sequence of zero or more paragraphs.
`contributionelementmetadata`:: attribution of the block to a specific contributor (<<contributionelementmetadata>>), to be used in change management of documents.

The Basic Document model recognises the following classes of block:

* Paragraphs (<<basicpara>>)
* Multi-paragraph blocks: Blockquotes, Reviewer comments, Admonitions (<<basicmultipara>>)
* Tables (<<basictable>>)
* Lists (<<basiclist>>): Unordered lists, Ordered lists, Definition lists
* Figures (<<basicfigure>>)
* Sourcecode (<<basicsourcecode>>)
* Formulas (<<basicformula>>)
* Examples (<<basicexample>>)

Functionally figures, sourcecode, formulas and examples all play a similar role, as providing illustrative content that is ancillary to the main content. However each class has its own particular structure.

[plantuml]
....
include::basicdoc_uml/Blocks.wsd[]
....


[[basicpara]]
==== Paragraph


Paragraphs can contain any sequence of inline elements (<<inline>>), and optionally a text alignment (`alignment`). 

NOTE: Text alignment is the only concession the modelling of paragraphs makes to rendering, and is there because the application of alignment to paragraphs, while rare, is unpredictable from paragraph semantics. Other rendering attributes of paragraphs, such as spacing before and after, are considered to be semantically predictable and are relegated to document stylesheets.

Paragraphs have the following subclass:

* _Paragraph With Footnote_, which can also contain footnotes (<<footnote>>). The distinction is necessary, as footnotes are not appropriate for all instances of paragraph content (e.g. sourcecode annotations) (<<basicsourcecode>>).

[[basicmultipara]]
==== Multi-paragraph blocks


The following classes of block are modelled as containing zero or more paragraphs:

* _Blockquote_, which also contains an optional bibliographic citation for the quotation (`source`), and an optional `author` of the quotation. The `author` attribute of the blockquote is redundant with the citation, since it restates  information about the author that should be recoverable from the citation itself. It is included for convenience, in case processing the citation is prohibitive for rendering tools, and is motivated by the separate inclusion of `author` as an attribute in blockquotes in Asciidoctor.
* _Admonition_, which captures sidebars to the main text conveying particular warnings to the reader. The Admonition block includes a type of admonition; the defined types for the Basic Document model are _Warning, Note, Tip, Important, and Caution_.
* [[review]]_Review_, which is intended to capture reviewer comments about some text in the document. The Review block includes the following attributes: an optional string identifying the `reviewer` who offered the comment; an optional `date` when the comment was made; a mandatory identifier for the start of the text to which the comment applies (`appliesFrom`), and an optional identifier for the end of the text to which the comment applies (`appliesTo`). 

NOTE: If the `appliesTo` identifier of a Review block is absent, the comment applies only to the span of text identified by the `appliesFrom` identifier; if it is present, the comments applies to the span of text between the start of the span of text identified by `appliesFrom`, and the end of the span of text identified by `appliesTo`.

NOTE: Admonition notes are modelled to be distinct from notes under sections or blocks.

[[basictable]]
==== Table


Tables are modelled consistently with HTML. They contain the following elements:

`name`:: An optional label for the table.
`head`:: Zero or more table rows constituting the table header.
`body`:: One or more table rows constituting the table body.
`foot`:: Zero or more table rows constituting the table footer.
`definitions`:: An optional definitions list (<<basiclist>>) defining any symbols used in the table. (This reflects practice in <<isoiecdir2>>.)

_Table rows_ are defined as a sequence of zero or more header cells and data cells (corresponding to HTML `th` and `td`), both classes being instances of table cells. 

_Table cells_ contain either zero or more paragraphs with footnotes (<<basicpara>>), or zero or more text elements (<<inline>>). In addition, they have the following optional rendering attributes consistent with HTML:

`colspan`:: Number of columns in the underlying table grid which the cell spans.
`rowspan`:: Number of rows in the underlying table grid which the cell spans.
`align`:: Textual alignment of the cell.


[[basiclist]]
==== List

Lists are modelled consistently with HTML. All lists contain zero or more _list items_, which by default consist of an identifier (`id`), and one or more paragraphs with footnotes (<<basicpara>>). This allows individual list items in a list to be cross-referenced within the document.

Three classes of list are modelled. 

* _Unordered lists_ are equivalent to the List base class. 
* _Ordered lists_ are Lists with a `type` attribute, describing the kind of numeration applied to the list; the values allowed under the Basic Document model are _roman, alphabet, arabic, roman_upper, alphabet_upper_, corresponding to lowercase Roman numerals, lowercase alphabetic letters, Arabic numerals, uppercase Roman numerals, and uppercase alphabetic letters.
* _Definition lists_ override the definition of the list item to be a pair of `item` (zero or more text elements: <<inline>>) and `definition` (zero or more paragraphs with footnotes: <<basicpara>>).


[[basicfigure]]
==== Figure

Figures are wrappers for images, and may themselves contain figures (_Subfigure_ class). They contain the following elements, all of which are optional:

`name`:: A label for the figure.
`image`:: An image (<<image>>).
`source`:: A URI or other reference intended to link to an externally hosted image (or equivalent).
`definitions`:: An optional definitions list (<<basiclist>>) defining any symbols used in the figure. (This reflects practice in <<isoiecdir2>>.)
`footnotes`:: Optional footnotes specific to the figure. (This reflects practice in <<isoiecdir2>>.)
`figure`:: Embedded figures. (This reflects practice in <<isoiecdir2>>, and subfigures are intended to be mutually exclusive with `image`, `source`: the latter are intended for leaf node figures.)

NOTE: The Basic Document model makes no provision for "Ascii art", the use of text instead of images. Models derived from the Basic Document model do permit such use of text by extending the modelling of figure.

[[basicsourcecode]]
==== Sourcecode

Sourcecode blocks are wrappers for computer code or comparable text. They contain the following elements:

`name`:: A label for the source code.
`content`:: The computer code or other such text presented in the block, as a single unformatted string. (The string should be treated as preformatted text, with whitespace treated as significant.)
`callouts`:: Zero or more cross-references (<<crossreferences>>); these are intended to be embedded within the `content` string, and link to annotations.
`calloutAnnotations`:: These are annotations to the source code; each annotation consists of zero or more paragraphs, and is intended to be referenced by a callout within the source code.

[[basicformula]]
==== Formula

Formula blocks are wrappers for mathematical or other formulas. They contain the following elements:

`stem`:: A STEM element (<<textelements>>), constituting the content of the formula
`definitions`:: An optional definitions list (<<basiclist>>) defining any symbols used in the formula. (This reflects practice in <<isoiecdir2>>.)

[[basicexample]]
==== Example

Example blocks are wrappers for open-ended example text. They consist of a combination of any of the following blocks:

* Formula
* List
* Blockquote (which is how generic text is included in an example)
* Sourcecode

// TODO: I don't think we've enforced the blockquote restriction; should we, or should we just allow text elements as an alternative here?

[[inline]]
=== Inline Elements

==== General

Inline elements represent the components of text blocks. They are modelled in the _Basic Document_ model as _Basic Elements_.

All Basic Elements have the following attribute:

`contributionelementmetadata`:: attribution of the element to a specific contributor (<<contributionelementmetadata>>), to be used in change management of documents.

Three subclasses of Basic Elements are modelled:

* Text elements, which contain text and associated formatting information, but which do not contain any associated identifiers. (<<textelements>>)
* ID elements, which contain identifiers. (<<image>>)
* Reference elements, which contain references to identifiers. (<<crossreferences>>)

Footnotes <<footnote>> are a special case of Reference element, which are not included under Basic Elements because of the need to exclude them from certain classes of paragraph (<<basicpara>>).

[[textelements]]
==== Text Elements

The modelling of text elements is substantially derived from HTML, and encompasses semantically significant formatting of text. For example, it encompasses italics and boldface (under their semantic guise of `emphasis` and `strong`); but it omits different sizes of font, as information that is typically semantically predictable, and relegated to stylesheets.

All text elements contain a localised string (<<datavalues>>).

The following elements indicate formatting, and have no further attributes:

* Monospace (corresponding to HTML `tt`, `code`)
* Emphasis (corresponding to HTML `em`, `i`)
* Strong (corresponding to HTML `strong`, `b`)
* Superscript (corresponding to HTML `sup`)
* Subscript (corresponding to HTML `sub`)
* Strike (corresponding to HTML 4 `s`)
* Small Caps 

Text Elements also include the STEM element, representing mathematical and other formulas. This consists of a `type`, indicating which language is used to express the formula, and the content of the formula itself. By default the Basic Document model allows AsciiMath and MathML in STEM elements.

NOTE: The _Basic Document_ model does not provide for text elements containing other text elements, for simplicity (e.g. monospace + italics, or superscript + strikethrough). Extensions to the model may choose to model such nesting of text elements.


==== Empty Elemnts

The following elements are subclasses of Basic Element that contain no text, and are intended to represent semantically significant formatting elements:

* Line Break (corresponding to HTML `br`)
* Page Break
* Horizontal Rule (corresponding to HTML `hr`)

[plantuml]
....
include::basicdoc_uml/TextElements.wsd[]
....


[[image]]
==== ID Elements

ID Elements are inline elements that have an identifier (`id`), which permits them to be cross-referenced by Reference Elements (<<crossreferences>>). ID Elements in the _Basic Documents_ model do not contain text.

There are two subclasses of ID Elements in the Basic Documents model:

* _Bookmarks_ are intended as anchors for cross-references which do not have scope over blocks or sections. The model under Basic Documents is that anchors within a block cannot span across a number of inline elements; bookmarks are intended as point anchors. For that reason, the Review block (<<review>>) has a starting reference and an optional ending reference, which can be bookmarks as well as block or section references.
* _Images_ are containers for pictorial content. They have a `source`, indicating the URI of the image file; a `type`, indicating the type of the image file; and an optional `height` and `width` attribute, which can be an integer or "auto".

NOTE: The Basic Documents_ model does not encompass audio and video files, but any extensions to the model would treat them likewise as ID Elements.

// TODO: We have not put alt text in; should we? We have not tackled accessibility in general.

[plantuml]
....
include::basicdoc_uml/TextElements.wsd[]
....


[[crossreferences]]
==== Reference Elements

Reference Elements are inline elements which reference other elements in the document, or other documents. All Reference Elements are modelled as containing the following attributes:

`text`:: The optional, unformatted textual content of the reference element.
`type`:: The type of Reference Element, prescribing how it is to be rendered. The _Basic Document_ model recognises four types: _inline_ (referencing another element in the same document), _external_ (referencing an external document), _footnote_ (an inline reference to be rendered as a footnote), and _callout_ (an inline reference to be rendered as a callout: <<basicsourcecode>>).

The following subclasses of Reference Elements are modelled.

* Reference to Link Element: An external reference, whose `target` is defined as a URI.
* Reference to Citation Element: An external reference to a bibliographic entity, as modelled in <<relaton>> as a _citation_. In addition to the attributes of _citation_, the reference has an optional `normative` attribute (which may be used by those standards which differentiate normative and informative references), and optional `citeAs` attributes prescribing how the bibliographic citation should be rendered in the text.
* Reference to ID Element: An internal reference, whose `target` corresponds to the identifier of a section, block or ID Element within the current document.

The Reference to ID Element class in turn has the following subclasses modelled:

* Callout, for which the `type` is set to _callout_, and the `text` is constrained to be a single mandatory string. The target of the callout is understood to be the location of the callout within the source code; the extent of the target is not expressed overtly.
* Reference To ID With Paragraph Element, which associates both `text` and `content` to the cross-reference; the `content` is a sequence of one or more paragraphs (<<basicpara>>).

[[footnote]]
==== Footnote

Footnotes are modelled as a subclass of Reference To ID With Paragraph Element, which constrain their `type` to be _footnote_. The `text` attribute is the footnote reference, and the `content` attribute is the footnote contents.  The target of the footnote is understood to be the location of the footnote within the text; the extent of the target is not expressed overtly.

NOTE: Endnotes are not modelled separately from footnotes in the _Basic Document_ model, and the use of footnotes and endnotes as realisations of annotations are normally stylistic alternatives, which would be relegated to a stylesheet.

[[datavalues]]
=== Data Values

[[contributionelementmetadata]]
==== Contribution Element Metadata

text

[[integrityvalue]]
==== Integrity Value

text

[[standardsdoc]]
== Standards Document Model

TODO: UML diagram

[[standardsdocument]]
=== Document

Text

[[standardssection]]
=== Section

Text
[[standardsblock]]
=== Block

Text


[[isoprofile]]
[appendix]
== ISO Standard Document Model Profile

The ISO Standard document model is given here as an exemplar of the application of Metanorma modelling to a particular standard

TODO: UML diagram

TODO: Grammar

[bibliography]
== Bibliography 

