= CalConnect Standard: Standardization document  -- Document metamodel

This work item belongs to TC VCARD.

image:https://github.com/CalConnect/csd-standard-doc/workflows/publish/badge.svg["Build Status", link="https://github.com/CalConnect/csd-standard-doc/actions?workflow=publish"]

This document is available in its rendered forms here:

* https://calconnect.github.io/csd-standard-doc/[CC/ISO: Standardization document  -- Document metamodel (HTML)]

== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/csd-standard-doc/
----

== Installing Build Tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=1
----

The `Makefile` will automatically choose the proper command to
execute.


== Building The Document

[source,sh]
----
bundle exec metanorma site generate
----

The following outputs will be built:

* CalConnect XML (https://github.com/calconnect/metanorma-model-cc) (`[filename].xml`)
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
* Word DOC (`[filename].doc`)


