
== Terms and definitions

////
=== body

responsible for standards and regulations: legal or administrative entity that has specific tasks and composition

NOTE: Examples of bodies are organizations, authorities, companies and foundations.

[.source]
<<isoguide2,4.1>>
////

=== standardizing body

body that has recognized activities in standardization

[.source]
<<isoguide2,clause=4.3>>


[[term-document]]
=== document

medium with information recorded on or in it

[.source]
<<isoguide2,clause=3.1 NOTE 2>>


[[term-standardization-document]]
=== standardization document

//[alt]#standard#

document that provides rules, guidelines or characteristics
for activities or their results

NOTE: Documents such as standards, technical specifications,
codes of practice and regulations are considered part of
this term.

NOTE: This terms closely corresponds to "`normative document`"
defined in <<isoguide2,clause=3.1>>.

////
model
conceptual data model
data model that represents an abstract view of the real world
Note 1 to entry: A conceptual model represents the human understanding of a system.
[SOURCE: ISO 11179-1:2004, definition 3.2.5]
ISO 23081-2:2009(en), 3.5


data model
graphical and/or lexical representation of data (3.2.6), specifying their properties, structure, and inter-relationships
ISO/IEC 11179-1:2015(en), 3.2.7

conceptual data model
data model (3.1.13.33) that represents an abstract view of the real world
Note 1 to entry: A conceptual model represents the human understanding of a system (3.1.1.13).
[SOURCE: ISO/IEC 11179-1:2015, definition 3.2.5]
Note 2 to entry: See also ISO 25964-1:2011; definition 2.14.
ISO 5127:2017(en), 3.1.13.34

data model
description of the organization of data (3.1.1.15) in a manner that reflects an information (3.1.1.16) structure
[SOURCE: ISO 28258:2013, definition 3.9]
ISO 5127:2017(en), 3.1.13.33

////

=== class

structure containing a description of an entity in terms of its components

=== subclass

term:[class] which inherits from another class its component descriptions, and optionally adds to them its own component descriptions

=== document metamodel

formal specification of the structure of a document model in terms of its components and their arrangement, expressed through term:[class,classes]


=== document model

formal specification of the structure of a document in terms of its components and their arrangement, expressed through term:[class,classes]


=== standards model

term:[document model] for
term:[standardization document,standardization documents]


=== paragraph

subdivision of running text, normally run on throughout, that is separated from text before and after by a change of line and stands below any chapters or term:[section,sections]

[.source]
<<iso5127,clause 3.5.8.07>>

=== block

grouping of text at the term:[paragraph] level

=== inline element

grouping of text that can be contained within a term:[paragraph], including plain strings


=== section

hierarchical subdivision of a document, consisting of one or more term:[block,blocks], and/or one or more sections

=== identifier

a character, or group of characters, used to identify or name an item of data and possibly to indicate certain properties of that item

[.source]
<<IEV,clause="714-21-07">>

=== term

expression with a particular meaning that is part of the specialized vocabulary of a field
