
[[structure]]
== Architecture

=== General

The _StandardDocument_ document metamodel is a semantically
oriented data model that depends on an underlying document model
for implementation.

_StandardDocument_ is closely aligned with the _BasicDocument_
model (<<basicdocument>>), but it can be implemented on top of any
document model that is compatible with the _BasicDocument_ model
or satisfies the requirements described in this document.


=== Dependent data models

The implementation of the document metamodel relies on the
availability of the following data models:

* A document data model that supports modeling of textual content
at the block and inline levels, as well as modifications to the
document itself.

* Data models for representing bibliographic information and citations
for a document.

In this document, the  _BasicDocument_ document model from
<<basicdocument>> is used as an exemplary document model,
the _BibliographicItem_ and its related data models from
<<relaton>> are used for representing bibliographic and
citation models.


=== Structure

The _StandardDocument_ document metamodel is expressed hierarchically
in the following structure:

* Document representation: the underlying document model,
described as _BasicDocument_ in this document, is
used to express the structure of generic documents
(with specific requirements detailed in the _BasicDocument_
model from <<basicdocument>>);

* Standardization document structure: the _StandardDocument_ model
is specialized from _BasicDocument_, conveying the structure particular
to standardization documents as a class.

* Specific types of standardization documents: the _StandardDocument_
model is further specialized into models specific to particular standards.
Specific standards models can form the basis in turn of other
standards models.


=== Underlying document model

The underlying document model must provide the following classes of
document element data models:

* Sections. A grouping of elements that can be shown under the
  table of contents (see the `Section` models in <<basicdocument>>)

* Blocks. A grouping of paragraphs or paragraph-levels of text
(see `Block` models in <<basicdocument>>)

* Inline elements. Groupings of text smaller than a paragraph,
including plain strings. (see `InlineElement` and related models in
<<basicdocument>>)


=== Bibliographic and citation models

Standardization documents often contain references to and citations
of external information resources, as well as bibliography sections.

The _StandardDocument_ model depends on data models that can fully
represent:

* metadata of referenced information resources;
* presentation of a referenced information resource; and
* locality of a citation.

For example, if a standardization document needs to adhere to the
citation guidelines of <<iso690>>, data models that facilitate these
rules such as <<relaton>> should be used.

The `BibliographicItem`, `Citation` and related models from <<relaton>> are
used in the reference metamodel for its expression of bibliographic
references and citations.


=== Hierarchical containment

In the document metamodel, the classes are in a strict hierarchical
relation:

* Documents consist of sections, which consist of blocks,
which consist of inline elements.

* Sections can be nested within sections (e.g. clauses and subclauses).

* Blocks can be nested within blocks (e.g. nested lists).

//Although the model does not currently provide for it,
* Inline elements can be embedded within other inline elements (e.g. bold with italics).

Sections in the _StandardDocument_ model are not expected to be
siblings of blocks, nor blocks of inline elements.

[example]
A list (block) is not expected to occur next to inline
text within a paragraph. For that reason, paragraphs cannot contain
other block elements, such as lists or tables.

NOTE: This constraint is adopted from <<basicdocument>>,
and is not present in XML-based schemas like HTML, TEI-C, or
DocBook. It confers the advantage of having a significantly streamlined
document model. While this limits some expressive potential,
the difference is minor and semantically desired, particularly
with regards to the unambiguous rendering of paragraphs.


=== Document model specialization

_StandardDocument_ can be specialized in the following ways:

* specializing classes from the _BasicDocument_ models;
* specializing classes from the _StandardDocument_ models;
* adding new classes;
* changing attributes of a class.

The specialization method is not restricted
to adding attributes, as is the case in typical entity subclassing;
it can also include removing attributes from a class, changing
their obligation and cardinality, and changing their type,
including changing enumerations. Attributes can be overruled at any
level; for example, standards-specific models routinely enhance the
bibliographic model at the base of the hierarchy.

For reasons of clarity, however, renaming classes and attributes should
be avoided in specialization.

[example]
The document model for the Chinese National Standard ("`GB Standard`"),
as described in <<gbt11>>, is structurally modelled after
ISO documents, explicitly described as a localization of ISO/IEC Directives Part 2, 2004.
Therefore, the Chinese National Standard model is best expressed
as a specialization of the ISO Standards model.


