
== Structure

The _StandardDocument_ document metamodel is expressed hierarchically.

* At its base is a `BasicDocument` model (<<basicdocument>>),
which expresses the structure of generic documents.

* The `BasicDocument` model is specialized as a _StandardsDocument_ structure, conveying the structure particular to
standardization documents as a class.

* The `StandardDocument` model is further specialized into models
specific to particular standards.

* Specific standards models can form the basis in turn of other
standards models.

[example]
The document model for the Chinese National Standard ("`GB Standard`"),
as described in <<gbt11>>, is structurally modelled after
ISO documents, explicitly described as a localization of the 2004 version of <<isoiecdir2-2004>>.
Therefore, the Chinese National Standard model is best expressed
as a specialization of the ISO Standards model.

Specialization of a model consists of:

* Adding classes to a base model.

* Changing attributes of a base model class. This is not restricted
to adding attributes, as is the case in typical entity subclassing;
it can also include removing attributes from a class, changing
their obligation and cardinality, and changing their type,
including changing enumerations. Attributes can be overruled at any
level; for example, standards-specific models routinely enhance the
bibliographic model at the base of the hierarchy.

* For reasons of clarity, renaming classes and attributes is
avoided in specialization.


The classes involved in the document model are of three classes:

* Sections (<<basicdocument>>, <<standardssection>>)

* Blocks (paragraph-level groupings of text) (<<basicdocument>>,
<<standardsblock>>)

* Inline elements (groupings of text smaller than a paragraph,
including plain strings) (<<basicdocument>>)


In the document metamodel, the classes are in a strict hierarchical
relation:

* Documents consist of sections, which consist of blocks,
which consist of inline elements.

* Sections can be nested within sections (e.g. clauses and subclauses)

* Blocks can be nested within blocks (e.g. nested lists).

//Although the model does not currently provide for it,
* Inline elements can be embedded within other inline elements (e.g. bold + italics).

However, sections in the _StandardsDocument_ model are not
expected to be siblings of blocks, nor blocks of inline elements.
For example, a list (block) is not expected to occur next to inline
text within a paragraph. For that reason, paragraphs cannot contain
other block elements, such as lists or tables.

NOTE: This constraint is inherited from lightweight text markup,
and is not present in XML-based schemas like HTML, TEI-C, or
DocBook. It helps to simplify the document model significantly, and
while it sacrifices some expressive potential, the difference is
minor, particularly with regards to the rendering of paragraphs.

The `BasicDocument` model contains the bulk of the blocks and
inline elements in the _StandardDocument_ model; that model is documented
separately (<<basicdocument>>), and is not discussed further here.
The Standards Model and the standard-specific models mostly deal
with the organization of sections within a standards document.
However, because _StandardDocument_ inherits from the `BasicDocument` model,
specialization in _StandardDocument_ can customize Basic Document classes,
as well as classes specific to Metanorma.

The document metamodel depends on the <<relaton>> citation
model for its expression of bibliographic references and citations.
