
[[metadata]]
== Document metadata elements

=== Purpose

Document metadata of a standardization document is used to
provide basic information of the standardization document.

This includes data elements such as:

* title(s);
* document identifier(s);
* authorship and contribution information;
* publisher and distributor details;
* rights information;
* document development stage;
* relevant dates; and
* edition.


=== Structure

Document metadata in _StandardDocument_ is handled using the
`StandardBibliographicItem` class extended from the
`BibliographicItem` class defined in <<relaton>>.

In standardization documents, certain data elements, such as
document identifiers and document development stage information,
are often highly specific to a standardization body.

Therefore, based on `BibliographicItem`, `StandardBibliographicItem`
implements the following extension points:

* the document type (already provided in the `BasicDocument` model),
it is assumed that particular specializations of the document metamodel
will substitute their own enumerations of particular subclasses of
document, which will be more granular;

* zero or more structured identifiers (<<structured-identifiers>>).

[datamodel_diagram,./models/views/Metadata.yml]

[datamodel_attributes_table,./models/models/BibDataExtensionType.yml]

[datamodel_attributes_table,./models/models/BibData.yml]

[datamodel_attributes_table,./models/models/StandardBibData.yml]

[datamodel_attributes_table,./models/models/StandardBibDataExtensionType.yml]



[[structured-identifiers]]
== Structured identifier

[datamodel_diagram,./models/views/StructuredIdentifier.yml]

[datamodel_attributes_table,./models/models/StructuredIdentifierType.yml]



