[[standardssection]]
== Section models

The _Standards Document_ model extends the _Basic Document_ modelling of sections by specialising the Basic Section class as follows:

* All sections in a _Standards Document_ model are instances of the Standard Section class, which is a subclass of Basic Section.
* The Standard Section class indicates its status as normative or informative explicitly, through the `status` attribute. (This attribute has been added because it is overtly specified in <<isoiecdir2>>, but the normative status of individual sections in a standard is pertinent to any standards document.)
* Sections in a standards document fall into two categories: Clause Sections, which are numbered, and form part of the main flow of the document, and Content sections (Standard Hierarchical Sections), which are optionally not numbered, and which lie outside the main flow of the document.
* The subclauses of Clauses are themselves Clause Sections; they continue the hierarchical numbering of Clause Sections at deeper hierarchical levels. The subclauses of Content sections are Standard Sections, and need not be numbered.
* Annexes and Clause Sections are modelled in the same way in the _Standards Document_ model. However they are expected to be numbered differently, and to be rendered as separate sequences.

Although it is different to capture in a container-based model, the _Standards Document_ model requires "hanging paragraphs" to be avoided: a Clause section in particular should contain either blocks or subsections, but not both. This is a requirement in <<isoiecdir2>>, but the need to reference text in clauses unambiguously by clause number makes the avoidance of hanging paragraphs desirable for standards documents in general. The requirement is less pressing for Content sections (which are unnumbered), and Annexes (as exemplified in <<isoiecdir2>> itself.)

.Standards Document model: Section
[plantuml]
....
include::models/standoc/StandardDoc_Sections.wsd[]
....
