
[[standardssection]]
== Section elements

=== Purpose

A section represents a clause in a standardization document.
Specifically, a section represents a logically coherent group of
paragraphs and blocks that is meant to be shown in the table
of contents.

=== Structure

The _StandardDocument_ model specializes the
`BasicSection` class of the _BasicDocument_ model as
follows:

* All sections in a _StandardDocument_ model are instances of the
`StandardSection` class, which is a subclass of `BasicSection`.

* The `StandardSection` class indicates its status as normative or
informative explicitly, through the `status` attribute.
The normative status of individual sections in a standardization
document is pertinent.

====
The necessity of indicating normative or informative `status`
is specified in <<ISOIECDIR2>> for ISO deliverables.
====

There are two major types of sections, namely, clause sections and
content sections.

=== Clause sections

Clause sections (`ClauseSection`) are numbered, and form part of the
main flow of the document.

Clause sections are by default hierarchical (as an exception, see <<terms>>).
The subclauses of Clauses are themselves Clause Sections; they
continue the hierarchical numbering of Clause Sections at deeper
hierarchical levels.

=== Content sections

Content sections (`StandardHierarchicalSection`) are optionally
not numbered, and lie outside the main flow of the document.

In _StandardDocument_, there are four distinctly named
content sections. These content sections are designated sections
as they recur in standardization documents and have distinct semantics:

* Abstract,
* Foreword,
* Introduction, and
* Acknowledgments.

Specializations of the model may define other such sections.

The subclauses of Content sections are ``StandardSection``s,
and need not be numbered.

=== Annex sections

Annexes are implemented as ``ClauseSection``s in the
_StandardDocument_ metamodel.

They are, however, expected to be numbered differently, and to be
rendered as separate sequences from clause sections.

=== Boilerplate sections

Boilerplate sections include recurring text that is included in all
documents of its class by the standardization body, and that reflects
various legal or policy requirements imposed on the document.

Boilerplate sections are implemented  as ``ContentSection``s in the
_StandardDocument_ metamodel.

They are, however, expected to be placed and rendered separately from the Content sections of the document.

In _StandardDocument_, there are four distinctly named
boilerplate sections. These content sections are designated sections
as they recur in standardization documents and have distinct semantics:

* Copyright Statement
* License Statement
* Legal Statement
* Feedback Statement

Specializations of the model may define other such sections.


=== Category label

Both section types can have a category label, which allows them
to be semantically classified into recurring categories, which
may be processed and rendered differently.
Indicative values include:

* `executive-summary`,
* `errata`,
* `methods`,
* `requirements`,
* `tests`,
* `reagents`, and
* `tests`.



=== Restrictions on hanging elements

Generally, in standardization documents there is a strong need
to reference text in clauses unambiguously by clause number,
which makes hanging paragraphs undesirable.

Therefore, the _StandardDocument_ model requires "hanging paragraphs"
to be avoided. In particular, its sections should
contain either blocks or subsections, but not both.

NOTE: The avoidance of "hanging paragraphs" is also a requirement in
<<ISOIECDIR2>>.

While this behavior is less pressing for Content sections (which are
unnumbered), and Annexes (as exemplified in <<ISOIECDIR2>>), it is
nonetheless not recommended.

lutaml_diagram::models/metanorma-model-standoc/views/StandardDoc_Sections.lutaml[]

=== Inherited from <<basicdocument>>

==== BasicSection
[lutaml_uml_attributes_table,models/metanorma-model-standoc/views/StandardDoc_Sections.lutaml,BasicSection, skip]

==== HierarchicalSection
[lutaml_uml_attributes_table,models/metanorma-model-standoc/views/StandardDoc_Sections.lutaml,HierarchicalSection, skip]

=== StandardDocument Elements, Generic

==== StandardSection
[lutaml_uml_attributes_table,models/metanorma-model-standoc/views/StandardDoc_Sections.lutaml,StandardSection, skip]

==== StandardHierarchicalSection
[lutaml_uml_attributes_table,models/metanorma-model-standoc/views/StandardDoc_Sections.lutaml,StandardHierarchicalSection, skip]

==== ClauseSection
[lutaml_uml_attributes_table,models/metanorma-model-standoc/views/StandardDoc_Sections.lutaml,ClauseSection, skip]

==== AnnexSection
[lutaml_uml_attributes_table,models/metanorma-model-standoc/views/StandardDoc_Sections.lutaml,AnnexSection, skip]

==== ClauseHierarchicalSection
[lutaml_uml_attributes_table,models/metanorma-model-standoc/views/StandardDoc_Sections.lutaml,ClauseHierarchicalSection, skip]

==== StandardContentSection
[lutaml_uml_attributes_table,models/metanorma-model-standoc/views/StandardDoc_Sections.lutaml,StandardContentSection, skip]

==== NormativeType
[lutaml_uml_attributes_table,models/metanorma-model-standoc/views/StandardDoc_Sections.lutaml,NormativeType, skip]

==== FloatingTitle
[lutaml_uml_attributes_table,models/metanorma-model-standoc/views/StandardDoc_Sections.lutaml,FloatingTitle, skip]

=== StandardDocument Elements, Prefatory

==== Abstract
[lutaml_uml_attributes_table,models/metanorma-model-standoc/views/StandardDoc_Sections.lutaml,Abstract, skip]

==== Foreword
[lutaml_uml_attributes_table,models/metanorma-model-standoc/views/StandardDoc_Sections.lutaml,Foreword, skip]

==== Introduction
[lutaml_uml_attributes_table,models/metanorma-model-standoc/views/StandardDoc_Sections.lutaml,Introduction, skip]

==== Acknowledgements
[lutaml_uml_attributes_table,models/metanorma-model-standoc/views/StandardDoc_Sections.lutaml,Acknowledgements, skip]


