
[[standardsreferencessection]]
== Citation and reference elements

=== Purpose

Standardization documents often cite other documents within,
and as a result they usually contain one or more bibliography sections
indicating its data sources. Bibliography sections may be differentiated
as being normative or informative.


lutaml_diagram::models/metanorma-model-standoc/views/StandardDoc_Sections.lutaml[]

[lutaml_uml_attributes_table,models/metanorma-model-standoc/views/StandardDoc_Sections.lutaml,StandardReferencesSection]

// I am forced to do this, because UML stereotypes are not rendered. I also currently cannot nest lutaml sections, their depth is hardcoded in the macro

(`ParagraphBlock` is taken from <<basicdocument>>. `BibliographicItem` is taken from <<relaton>>.)

[lutaml_uml_attributes_table,models/metanorma-model-standoc/views/StandardDoc_Inline.lutaml,StandocReferenceToCitationElement]

(References to citations are specialisations of `ReferenceToCitationElement` taken from <<basicdocument>>.)

// [lutaml_uml_attributes_table,./models/models/Citation.yml]


=== Reference item

Each reference item is represented using the `BibliographicItem`
class defined in <<relaton>>.

It is not necessary to specialize reference items amongst
documents from different standardization bodies as a document
can cite documents of any type.


=== Citation

Each citation is represented by the `Citation` class defined in
<<relaton>>.

It is not necessary to specialize citations since it is simply
a document data element reference linked to a reference item.

References to citations are specialisations of `ReferenceToCitationElement` taken from <<basicdocument>>.

